#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
68_train_and_evaluate_cadrg_chronological_ridgecrest.py

Step 5: Chronological extrapolation + Ridgecrest sequence-level OOD
for the final CA-DRG model.

Chronological protocol
----------------------
train:
    2010-2018
validation:
    2019 non-Ridgecrest + 2020
test:
    2021-2024
ridgecrest_ood:
    complete held-out 2019 Ridgecrest sequence

The split is supplied by the existing time-clean manifest:
    scenario_t0_5s_k5_time_clean.csv
with:
    split_time_clean

Model
-----
A2-time:
    Cross-Attention Base

A6-time:
    CA-DRG
    y_final = y_base + p_under * p_tail**gamma * Delta

Selection protocol
------------------
1. Retrain Cross-Attention using chronological TRAIN only.
2. Select Base checkpoint using chronological VALIDATION only.
3. Reuse the TRAIN-only chronological Q90 threshold JSON generated by the
   previous clean-time pipeline for the SAME split/task.
4. Freeze Base.
5. Train Dual-Risk head on chronological TRAIN only.
6. Jointly select head epoch + gamma on 20-repeat chronological VALIDATION.
7. OOD/shift-aware preservation guards:
       overall MAE increase <= 0.005 for both PGA/PGV
       non-tail MAE increase <= 0.003 for both PGA/PGV
       |bias_candidate| <= |bias_base| + 0.005 for both PGA/PGV
8. If the selected gamma is not at the upper grid boundary, freeze everything.
9. Evaluate ONCE on:
       (a) 2021-2024 chronological test
       (b) full Ridgecrest sequence-level OOD

No 2021-2024 or Ridgecrest event is used for checkpoint/gamma selection.

Canonical metric aggregation
----------------------------
targets -> repeats -> events

Required local modules
----------------------
45_phase2_strong_baseline_suite.py
60_train_cross_attention_dual_risk_joint_selection.py
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import random
import shutil
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader


LOG10_FACTOR_2 = math.log10(2.0)
LOG10_FACTOR_3 = math.log10(3.0)
SEVERE_UNDER_THRESHOLD = -0.5


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------

def load_module(
    path: str | Path,
    name: str,
):
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"Required module not found: {path.resolve()}"
        )

    spec = importlib.util.spec_from_file_location(
        name,
        str(path),
    )

    if spec is None or spec.loader is None:
        raise ImportError(
            f"Cannot import module: {path}"
        )

    module = importlib.util.module_from_spec(
        spec
    )

    spec.loader.exec_module(
        module
    )

    return module


def load_checkpoint(
    path: str | Path,
    device: torch.device,
):
    try:
        return torch.load(
            str(path),
            map_location=device,
            weights_only=False,
        )
    except TypeError:
        return torch.load(
            str(path),
            map_location=device,
        )


def set_seed(
    seed: int,
) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def parse_float_list(
    text: str,
) -> list[float]:
    values = []

    for token in str(text).split(","):
        token = token.strip()

        if not token:
            continue

        value = float(token)

        if value < 1.0:
            raise ValueError(
                "Gamma values must be >= 1."
            )

        values.append(
            value
        )

    values = sorted(
        set(values)
    )

    if not values:
        raise ValueError(
            "No gamma values supplied."
        )

    return values


# ---------------------------------------------------------------------
# Dataset helpers
# ---------------------------------------------------------------------

def make_dataset(
    baseline_module,
    args,
    split_name: str,
    training: bool,
    repeats: int,
):
    return (
        baseline_module
        .StrongBaselineDataset(
            manifest=args.manifest,
            h5_root=args.h5_root,
            split_column=args.split_column,
            split_name=split_name,
            t0_sec=args.t0_sec,
            input_stations=args.input_stations,
            target_stations=args.target_stations,
            input_pre_sec=args.input_pre_sec,
            seed=args.seed,
            training=training,
            repeats=(
                repeats
            ),
        )
    )


def make_loader(
    dataset,
    args,
    device: torch.device,
    shuffle: bool,
    generator: torch.Generator | None = None,
):
    return DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=shuffle,
        generator=generator,
        num_workers=args.num_workers,
        pin_memory=(
            device.type
            == "cuda"
        ),
        persistent_workers=(
            args.num_workers
            > 0
        ),
    )


# ---------------------------------------------------------------------
# Chronological Cross-Attention Base
# ---------------------------------------------------------------------

def train_chronological_base(
    baseline_module,
    args,
    device: torch.device,
    out_dir: Path,
) -> tuple[
    nn.Module,
    dict[str, Any],
]:
    train_dataset = make_dataset(
        baseline_module,
        args,
        args.train_label,
        training=True,
        repeats=1,
    )

    validation_dataset = make_dataset(
        baseline_module,
        args,
        args.validation_label,
        training=False,
        repeats=args.base_validation_repeats,
    )

    generator = torch.Generator()
    generator.manual_seed(
        args.seed
    )

    train_loader = make_loader(
        train_dataset,
        args,
        device,
        shuffle=True,
        generator=generator,
    )

    validation_loader = make_loader(
        validation_dataset,
        args,
        device,
        shuffle=False,
    )

    model = baseline_module.make_model(
        "cross_attention",
        args.hidden_dim,
        args.attention_heads,
        50.0,
    ).to(
        device
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.base_learning_rate,
        weight_decay=args.base_weight_decay,
    )

    scheduler = (
        torch.optim.lr_scheduler
        .ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=0.5,
            patience=args.base_lr_patience,
            min_lr=args.base_minimum_learning_rate,
        )
    )

    base_dir = (
        out_dir
        / "cross_attention_base"
    )

    base_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    best_path = (
        base_dir
        / "best_model.pt"
    )

    best_score = np.inf
    best_epoch = 0
    stale = 0
    history = []

    print(
        "\n=== Step 5A: chronological "
        "Cross-Attention Base training ==="
    )

    print(
        f"Train events              : "
        f"{len(train_dataset.frame)}"
    )

    print(
        f"Validation events         : "
        f"{len(validation_dataset.frame)}"
    )

    print(
        f"Validation repeats        : "
        f"{args.base_validation_repeats}"
    )

    print(
        f"Parameters                : "
        f"{sum(p.numel() for p in model.parameters()):,}"
    )

    for epoch in range(
        1,
        args.base_epochs
        + 1,
    ):
        train_dataset.set_epoch(
            epoch
        )

        train_loss = (
            baseline_module.train_epoch(
                model,
                train_loader,
                optimizer,
                device,
            )
        )

        val_frame = (
            baseline_module.predict_model(
                model,
                validation_loader,
                device,
            )
        )

        val_pga = (
            baseline_module.event_balanced_mae(
                val_frame,
                "pga",
                "pred_log10_pga",
            )
        )

        val_pgv = (
            baseline_module.event_balanced_mae(
                val_frame,
                "pgv",
                "pred_log10_pgv",
            )
        )

        score = 0.5 * (
            val_pga
            + val_pgv
        )

        scheduler.step(
            score
        )

        learning_rate = float(
            optimizer.param_groups[
                0
            ][
                "lr"
            ]
        )

        history.append(
            {
                "epoch": epoch,
                "train_loss": train_loss,
                "validation_mae_pga": val_pga,
                "validation_mae_pgv": val_pgv,
                "validation_score": score,
                "learning_rate": learning_rate,
            }
        )

        pd.DataFrame(
            history
        ).to_csv(
            base_dir
            / "history.csv",
            index=False,
        )

        print(
            f"Base epoch {epoch:03d} | "
            f"train={train_loss:.4f} | "
            f"val PGA={val_pga:.4f} | "
            f"PGV={val_pgv:.4f} | "
            f"score={score:.4f} | "
            f"lr={learning_rate:.2e}"
        )

        if (
            score
            < best_score
            - args.base_minimum_delta
        ):
            best_score = (
                score
            )
            best_epoch = (
                epoch
            )
            stale = 0

            torch.save(
                {
                    "variant": (
                        "cross_attention"
                    ),
                    "model_state": (
                        model.state_dict()
                    ),
                    "epoch": (
                        epoch
                    ),
                    "validation_mae_pga": (
                        val_pga
                    ),
                    "validation_mae_pgv": (
                        val_pgv
                    ),
                    "validation_score": (
                        score
                    ),
                    "chronological_training": (
                        True
                    ),
                    "args": vars(
                        args
                    ),
                },
                best_path,
            )

        else:
            stale += 1

        if (
            stale
            >= args.base_early_stopping_patience
        ):
            print(
                "Base early stopping at "
                f"epoch {epoch}; "
                f"best epoch={best_epoch}"
            )
            break

    checkpoint = load_checkpoint(
        best_path,
        device,
    )

    model.load_state_dict(
        checkpoint[
            "model_state"
        ],
        strict=True,
    )

    model.eval()

    summary = {
        "best_epoch": int(
            checkpoint[
                "epoch"
            ]
        ),
        "validation_mae_pga": float(
            checkpoint[
                "validation_mae_pga"
            ]
        ),
        "validation_mae_pgv": float(
            checkpoint[
                "validation_mae_pgv"
            ]
        ),
        "validation_score": float(
            checkpoint[
                "validation_score"
            ]
        ),
        "train_events": int(
            len(
                train_dataset.frame
            )
        ),
        "validation_events": int(
            len(
                validation_dataset.frame
            )
        ),
        "checkpoint": str(
            best_path.resolve()
        ),
    }

    (
        base_dir
        / "base_selection_summary.json"
    ).write_text(
        json.dumps(
            summary,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        "\nSelected chronological "
        "Cross-Attention Base:"
    )

    print(
        f"  epoch="
        f"{summary['best_epoch']}"
    )

    print(
        "  val PGA/PGV="
        f"{summary['validation_mae_pga']:.4f}/"
        f"{summary['validation_mae_pgv']:.4f}"
    )

    return (
        model,
        summary,
    )


# ---------------------------------------------------------------------
# Frozen-base caches
# ---------------------------------------------------------------------

def build_cache(
    base: nn.Module,
    loader: DataLoader,
    thresholds: np.ndarray,
    device: torch.device,
    risk_module,
) -> dict[str, Any]:
    risk_feature_parts = []
    base_parts = []
    truth_parts = []
    target_index_parts = []
    target_slot_parts = []

    event_ids = []
    repeats = []

    base.eval()

    with torch.inference_mode():
        for batch in loader:
            truth = (
                batch[
                    "target_log"
                ]
                .numpy()
            )

            (
                base_prediction,
                risk_feature,
            ) = (
                risk_module
                .cross_attention_base_context(
                    base,
                    batch[
                        "input_waveforms"
                    ].to(
                        device
                    ),
                    batch[
                        "input_features"
                    ].to(
                        device
                    ),
                    batch[
                        "target_features"
                    ].to(
                        device
                    ),
                )
            )

            risk_feature_parts.append(
                risk_feature
                .cpu()
                .numpy()
            )

            base_parts.append(
                base_prediction
                .cpu()
                .numpy()
            )

            truth_parts.append(
                truth
            )

            target_index_parts.append(
                batch[
                    "target_station_index"
                ].numpy()
            )

            target_slot_parts.append(
                batch[
                    "target_slot"
                ].numpy()
            )

            batch_event_ids = list(
                batch[
                    "event_id"
                ]
            )

            batch_repeats = (
                batch[
                    "repeat"
                ]
                .numpy()
            )

            for b in range(
                truth.shape[
                    0
                ]
            ):
                for _ in range(
                    truth.shape[
                        1
                    ]
                ):
                    event_ids.append(
                        str(
                            batch_event_ids[
                                b
                            ]
                        )
                    )

                    repeats.append(
                        int(
                            batch_repeats[
                                b
                            ]
                        )
                    )

    risk_feature = np.concatenate(
        risk_feature_parts,
        axis=0,
    ).reshape(
        -1,
        risk_feature_parts[
            0
        ].shape[
            -1
        ],
    )

    base_prediction = np.concatenate(
        base_parts,
        axis=0,
    ).reshape(
        -1,
        2,
    )

    truth = np.concatenate(
        truth_parts,
        axis=0,
    ).reshape(
        -1,
        2,
    )

    target_indices = np.concatenate(
        target_index_parts,
        axis=0,
    ).reshape(
        -1
    )

    target_slots = np.concatenate(
        target_slot_parts,
        axis=0,
    ).reshape(
        -1
    )

    tail = (
        truth
        >= thresholds[
            None,
            :,
        ]
    )

    under = (
        (
            base_prediction
            - truth
        )
        <= SEVERE_UNDER_THRESHOLD
    )

    return {
        "risk_feature": risk_feature.astype(
            np.float32
        ),
        "base": base_prediction.astype(
            np.float64
        ),
        "truth": truth.astype(
            np.float64
        ),
        "tail": tail.astype(
            bool
        ),
        "under": under.astype(
            bool
        ),
        "event_id": np.asarray(
            event_ids,
            dtype=object,
        ),
        "repeat": np.asarray(
            repeats,
            dtype=np.int64,
        ),
        "target_station_index": (
            target_indices.astype(
                np.int64
            )
        ),
        "target_slot": (
            target_slots.astype(
                np.int64
            )
        ),
    }


# ---------------------------------------------------------------------
# Relative-bias feasibility
# ---------------------------------------------------------------------

def relative_bias_status(
    candidate: dict[str, float],
    base: dict[str, float],
    overall_budget: float,
    non_tail_budget: float,
    bias_margin: float,
) -> dict[str, Any]:
    result = {}
    conditions = []

    for quantity in (
        "pga",
        "pgv",
    ):
        overall_delta = (
            candidate[
                f"overall_mae_{quantity}"
            ]
            - base[
                f"overall_mae_{quantity}"
            ]
        )

        non_tail_delta = (
            candidate[
                f"non_tail_mae_{quantity}"
            ]
            - base[
                f"non_tail_mae_{quantity}"
            ]
        )

        tail_delta = (
            candidate[
                f"tail_mae_{quantity}"
            ]
            - base[
                f"tail_mae_{quantity}"
            ]
        )

        tail_u05_delta = (
            candidate[
                f"tail_under05_{quantity}"
            ]
            - base[
                f"tail_under05_{quantity}"
            ]
        )

        base_bias = float(
            base[
                f"bias_{quantity}"
            ]
        )

        candidate_bias = float(
            candidate[
                f"bias_{quantity}"
            ]
        )

        relative_bias_limit = (
            abs(
                base_bias
            )
            + float(
                bias_margin
            )
        )

        result[
            f"overall_delta_{quantity}"
        ] = overall_delta

        result[
            f"non_tail_delta_{quantity}"
        ] = non_tail_delta

        result[
            f"tail_delta_{quantity}"
        ] = tail_delta

        result[
            f"tail_under05_delta_{quantity}"
        ] = tail_u05_delta

        result[
            f"relative_bias_limit_{quantity}"
        ] = relative_bias_limit

        result[
            f"pass_overall_{quantity}"
        ] = bool(
            overall_delta
            <= float(
                overall_budget
            )
        )

        result[
            f"pass_non_tail_{quantity}"
        ] = bool(
            non_tail_delta
            <= float(
                non_tail_budget
            )
        )

        result[
            f"pass_relative_bias_{quantity}"
        ] = bool(
            abs(
                candidate_bias
            )
            <= relative_bias_limit
        )

        conditions.extend(
            [
                result[
                    f"pass_overall_{quantity}"
                ],
                result[
                    f"pass_non_tail_{quantity}"
                ],
                result[
                    f"pass_relative_bias_{quantity}"
                ],
            ]
        )

    result[
        "feasible"
    ] = bool(
        all(
            conditions
        )
    )

    return result


# ---------------------------------------------------------------------
# Dual-Risk head training + validation selection
# ---------------------------------------------------------------------

def train_and_select_dual_risk(
    baseline_module,
    risk_module,
    args,
    base: nn.Module,
    thresholds: np.ndarray,
    device: torch.device,
    out_dir: Path,
) -> tuple[
    nn.Module | None,
    dict[str, Any],
]:
    head_dir = (
        out_dir
        / "dual_risk_head"
    )

    checkpoint_dir = (
        head_dir
        / "epoch_checkpoints"
    )

    checkpoint_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    prevalence_dataset = make_dataset(
        baseline_module,
        args,
        args.train_label,
        training=False,
        repeats=args.prevalence_repeats,
    )

    prevalence_loader = make_loader(
        prevalence_dataset,
        args,
        device,
        shuffle=False,
    )

    prevalence_cache = build_cache(
        base,
        prevalence_loader,
        thresholds,
        device,
        risk_module,
    )

    tail_prevalence = (
        prevalence_cache[
            "tail"
        ].mean(
            axis=0
        )
    )

    under_prevalence = (
        prevalence_cache[
            "under"
        ].mean(
            axis=0
        )
    )

    tail_pos_weight_np = np.clip(
        (
            1.0
            - tail_prevalence
        )
        / np.maximum(
            tail_prevalence,
            1e-6,
        ),
        1.0,
        args.max_positive_weight,
    )

    under_pos_weight_np = np.clip(
        (
            1.0
            - under_prevalence
        )
        / np.maximum(
            under_prevalence,
            1e-6,
        ),
        1.0,
        args.max_positive_weight,
    )

    tail_pos_weight = torch.as_tensor(
        tail_pos_weight_np,
        dtype=torch.float32,
        device=device,
    )

    under_pos_weight = torch.as_tensor(
        under_pos_weight_np,
        dtype=torch.float32,
        device=device,
    )

    model = (
        risk_module
        .CrossAttentionDualRiskGate(
            base=base,
            hidden_dim=args.hidden_dim,
            risk_hidden=args.risk_hidden,
            maximum_correction=(
                args.maximum_correction
            ),
            tail_prevalence=(
                tail_prevalence
            ),
            under_prevalence=(
                under_prevalence
            ),
        )
        .to(
            device
        )
    )

    train_dataset = make_dataset(
        baseline_module,
        args,
        args.train_label,
        training=True,
        repeats=1,
    )

    generator = torch.Generator()
    generator.manual_seed(
        args.seed
        + 777
    )

    train_loader = make_loader(
        train_dataset,
        args,
        device,
        shuffle=True,
        generator=generator,
    )

    monitor_dataset = make_dataset(
        baseline_module,
        args,
        args.validation_label,
        training=False,
        repeats=args.head_monitor_repeats,
    )

    monitor_loader = make_loader(
        monitor_dataset,
        args,
        device,
        shuffle=False,
    )

    monitor_cache = build_cache(
        base,
        monitor_loader,
        thresholds,
        device,
        risk_module,
    )

    selection_dataset = make_dataset(
        baseline_module,
        args,
        args.validation_label,
        training=False,
        repeats=args.head_selection_repeats,
    )

    selection_loader = make_loader(
        selection_dataset,
        args,
        device,
        shuffle=False,
    )

    selection_cache = build_cache(
        base,
        selection_loader,
        thresholds,
        device,
        risk_module,
    )

    base_validation_metrics = (
        risk_module.metric_bundle(
            selection_cache,
            selection_cache[
                "base"
            ],
        )
    )

    trainable = [
        parameter
        for parameter
        in model.parameters()
        if parameter.requires_grad
    ]

    optimizer = torch.optim.AdamW(
        trainable,
        lr=args.head_learning_rate,
        weight_decay=args.head_weight_decay,
    )

    scheduler = (
        torch.optim.lr_scheduler
        .ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=0.5,
            patience=3,
            min_lr=1e-5,
        )
    )

    threshold_tensor = torch.as_tensor(
        thresholds,
        dtype=torch.float32,
        device=device,
    )

    history = []

    print(
        "\n=== Step 5B: chronological "
        "Dual-Risk head training ==="
    )

    print(
        "TRAIN tail prevalence PGA/PGV : "
        f"{tail_prevalence[0]:.4f}/"
        f"{tail_prevalence[1]:.4f}"
    )

    print(
        "TRAIN U0.5 prevalence PGA/PGV : "
        f"{under_prevalence[0]:.4f}/"
        f"{under_prevalence[1]:.4f}"
    )

    print(
        "Frozen Base val overall PGA/PGV: "
        f"{base_validation_metrics['overall_mae_pga']:.4f}/"
        f"{base_validation_metrics['overall_mae_pgv']:.4f}"
    )

    print(
        "Frozen Base val bias PGA/PGV   : "
        f"{base_validation_metrics['bias_pga']:+.4f}/"
        f"{base_validation_metrics['bias_pgv']:+.4f}"
    )

    print(
        "Frozen Base val tail PGA/PGV   : "
        f"{base_validation_metrics['tail_mae_pga']:.4f}/"
        f"{base_validation_metrics['tail_mae_pgv']:.4f}"
    )

    for epoch in range(
        1,
        args.head_epochs
        + 1,
    ):
        train_dataset.set_epoch(
            epoch
        )

        train_metrics = (
            risk_module.train_epoch(
                model=model,
                loader=train_loader,
                optimizer=optimizer,
                device=device,
                thresholds=threshold_tensor,
                tail_pos_weight=tail_pos_weight,
                under_pos_weight=under_pos_weight,
                lambda_tail_classification=(
                    args.lambda_tail_classification
                ),
                lambda_under_classification=(
                    args.lambda_under_classification
                ),
                lambda_regression=(
                    args.lambda_regression
                ),
                risk_regression_weight=(
                    args.risk_regression_weight
                ),
                lambda_directional=(
                    args.lambda_directional
                ),
                lambda_leakage=(
                    args.lambda_leakage
                ),
            )
        )

        head_now = (
            risk_module
            .predict_head_from_cache(
                model,
                monitor_cache[
                    "risk_feature"
                ],
                device,
                args.head_eval_batch_size,
            )
        )

        monitor_prediction = (
            monitor_cache[
                "base"
            ]
            + head_now[
                "under_probability"
            ]
            * head_now[
                "tail_probability"
            ]
            * head_now[
                "residual"
            ]
        )

        monitor_metrics = (
            risk_module.metric_bundle(
                monitor_cache,
                monitor_prediction,
            )
        )

        scheduler.step(
            monitor_metrics[
                "mean_overall_mae"
            ]
        )

        checkpoint_path = (
            checkpoint_dir
            / f"epoch_{epoch:03d}.pt"
        )

        torch.save(
            {
                "model_state": (
                    model.state_dict()
                ),
                "epoch": (
                    epoch
                ),
                "chronological_training": (
                    True
                ),
                "tail_prevalence": (
                    tail_prevalence.tolist()
                ),
                "under_prevalence": (
                    under_prevalence.tolist()
                ),
                "test_accessed": (
                    False
                ),
                "ridgecrest_accessed": (
                    False
                ),
            },
            checkpoint_path,
        )

        history.append(
            {
                "epoch": epoch,
                "learning_rate": float(
                    optimizer.param_groups[
                        0
                    ][
                        "lr"
                    ]
                ),
                **{
                    f"train_{key}": value
                    for key, value
                    in train_metrics.items()
                },
                **{
                    f"monitor_{key}": value
                    for key, value
                    in monitor_metrics.items()
                },
            }
        )

        pd.DataFrame(
            history
        ).to_csv(
            head_dir
            / "history.csv",
            index=False,
        )

        print(
            f"Head epoch {epoch:03d} | "
            f"loss={train_metrics['loss']:.4f} | "
            "val overall="
            f"{monitor_metrics['overall_mae_pga']:.4f}/"
            f"{monitor_metrics['overall_mae_pgv']:.4f} | "
            "tail="
            f"{monitor_metrics['tail_mae_pga']:.4f}/"
            f"{monitor_metrics['tail_mae_pgv']:.4f} | "
            "U05="
            f"{monitor_metrics['tail_under05_pga']:.3f}/"
            f"{monitor_metrics['tail_under05_pgv']:.3f}"
        )

    powers = parse_float_list(
        args.powers
    )

    scan_rows = []

    for epoch in range(
        1,
        args.head_epochs
        + 1,
    ):
        checkpoint = load_checkpoint(
            checkpoint_dir
            / f"epoch_{epoch:03d}.pt",
            device,
        )

        model.load_state_dict(
            checkpoint[
                "model_state"
            ],
            strict=True,
        )

        head = (
            risk_module
            .predict_head_from_cache(
                model,
                selection_cache[
                    "risk_feature"
                ],
                device,
                args.head_eval_batch_size,
            )
        )

        for gamma in powers:
            prediction = (
                selection_cache[
                    "base"
                ]
                + head[
                    "under_probability"
                ]
                * np.power(
                    np.clip(
                        head[
                            "tail_probability"
                        ],
                        0.0,
                        1.0,
                    ),
                    gamma,
                )
                * head[
                    "residual"
                ]
            )

            metrics = (
                risk_module.metric_bundle(
                    selection_cache,
                    prediction,
                )
            )

            status = relative_bias_status(
                candidate=metrics,
                base=base_validation_metrics,
                overall_budget=args.overall_budget,
                non_tail_budget=args.non_tail_budget,
                bias_margin=args.bias_margin,
            )

            scan_rows.append(
                {
                    "epoch": epoch,
                    "gamma": gamma,
                    **metrics,
                    **status,
                }
            )

    scan = pd.DataFrame(
        scan_rows
    )

    scan.to_csv(
        head_dir
        / "epoch_gamma_validation_scan.csv",
        index=False,
    )

    feasible = scan.loc[
        scan[
            "feasible"
        ].astype(
            bool
        )
    ].copy()

    if feasible.empty:
        failure = {
            "status": (
                "no_feasible_candidate"
            ),
            "base_validation_metrics": (
                base_validation_metrics
            ),
            "overall_budget": float(
                args.overall_budget
            ),
            "non_tail_budget": float(
                args.non_tail_budget
            ),
            "bias_margin": float(
                args.bias_margin
            ),
            "bias_rule": (
                "|bias_candidate| <= "
                "|bias_base| + bias_margin"
            ),
            "test_accessed": False,
            "ridgecrest_accessed": False,
        }

        (
            head_dir
            / "selection_failure.json"
        ).write_text(
            json.dumps(
                failure,
                indent=2,
            ),
            encoding="utf-8",
        )

        print(
            "\nNO chronological Dual-Risk candidate "
            "satisfied all validation constraints."
        )

        print(
            "2021-2024 test: NOT ACCESSED"
        )

        print(
            "Ridgecrest OOD : NOT ACCESSED"
        )

        return (
            None,
            failure,
        )

    feasible = feasible.sort_values(
        [
            "mean_tail_mae",
            "mean_tail_under05",
            "mean_overall_mae",
            "gamma",
            "epoch",
        ],
        ascending=[
            True,
            True,
            True,
            True,
            True,
        ],
    )

    feasible.to_csv(
        head_dir
        / "feasible_validation_candidates.csv",
        index=False,
    )

    selected = feasible.iloc[
        0
    ]

    selected_epoch = int(
        selected[
            "epoch"
        ]
    )

    selected_gamma = float(
        selected[
            "gamma"
        ]
    )

    upper_boundary = bool(
        np.isclose(
            selected_gamma,
            max(
                powers
            ),
        )
    )

    selected_source = (
        checkpoint_dir
        / f"epoch_{selected_epoch:03d}.pt"
    )

    selected_checkpoint_path = (
        head_dir
        / "selected_dual_risk_head.pt"
    )

    shutil.copy2(
        selected_source,
        selected_checkpoint_path,
    )

    selected_checkpoint = load_checkpoint(
        selected_checkpoint_path,
        device,
    )

    model.load_state_dict(
        selected_checkpoint[
            "model_state"
        ],
        strict=True,
    )

    model.eval()

    selection = {
        "status": "selected",
        "selected_epoch": selected_epoch,
        "selected_gamma": selected_gamma,
        "selected_at_upper_gamma_boundary": (
            upper_boundary
        ),
        "feasible_candidates": int(
            len(
                feasible
            )
        ),
        "total_candidates": int(
            len(
                scan
            )
        ),
        "base_validation_metrics": (
            base_validation_metrics
        ),
        "selected_validation_metrics": {
            key: (
                bool(value)
                if isinstance(
                    value,
                    (
                        bool,
                        np.bool_,
                    ),
                )
                else (
                    int(value)
                    if isinstance(
                        value,
                        (
                            int,
                            np.integer,
                        ),
                    )
                    else (
                        float(value)
                        if isinstance(
                            value,
                            (
                                float,
                                np.floating,
                            ),
                        )
                        else value
                    )
                )
            )
            for key, value
            in selected.to_dict().items()
        },
        "overall_budget": float(
            args.overall_budget
        ),
        "non_tail_budget": float(
            args.non_tail_budget
        ),
        "bias_margin": float(
            args.bias_margin
        ),
        "bias_rule": (
            "|bias_candidate| <= "
            "|bias_base| + bias_margin"
        ),
        "test_accessed": False,
        "ridgecrest_accessed": False,
    }

    (
        head_dir
        / "selected_epoch_gamma.json"
    ).write_text(
        json.dumps(
            selection,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        "\n=== Selected chronological CA-DRG ==="
    )

    print(
        f"Epoch                      : "
        f"{selected_epoch}"
    )

    print(
        f"Gamma                      : "
        f"{selected_gamma:g}"
    )

    print(
        f"At upper gamma boundary    : "
        f"{upper_boundary}"
    )

    print(
        "Overall MAE PGA/PGV        : "
        f"{selected['overall_mae_pga']:.4f}/"
        f"{selected['overall_mae_pgv']:.4f}"
    )

    print(
        "Overall delta PGA/PGV      : "
        f"{selected['overall_delta_pga']:+.4f}/"
        f"{selected['overall_delta_pgv']:+.4f}"
    )

    print(
        "Non-tail delta PGA/PGV     : "
        f"{selected['non_tail_delta_pga']:+.4f}/"
        f"{selected['non_tail_delta_pgv']:+.4f}"
    )

    print(
        "Bias PGA/PGV               : "
        f"{selected['bias_pga']:+.4f}/"
        f"{selected['bias_pgv']:+.4f}"
    )

    print(
        "Tail MAE PGA/PGV           : "
        f"{selected['tail_mae_pga']:.4f}/"
        f"{selected['tail_mae_pgv']:.4f}"
    )

    print(
        "Tail delta PGA/PGV         : "
        f"{selected['tail_delta_pga']:+.4f}/"
        f"{selected['tail_delta_pgv']:+.4f}"
    )

    print(
        "Tail U0.5 PGA/PGV          : "
        f"{selected['tail_under05_pga']:.3f}/"
        f"{selected['tail_under05_pgv']:.3f}"
    )

    print(
        f"Feasible candidates        : "
        f"{len(feasible)}/{len(scan)}"
    )

    if upper_boundary:
        print(
            "\nSelected gamma is at the "
            "upper VALIDATION boundary."
        )

        print(
            "Extend gamma using validation only."
        )

        print(
            "2021-2024 test: NOT ACCESSED"
        )

        print(
            "Ridgecrest OOD : NOT ACCESSED"
        )

        return (
            None,
            selection,
        )

    return (
        model,
        selection,
    )


# ---------------------------------------------------------------------
# Locked split evaluation
# ---------------------------------------------------------------------

def evaluate_split(
    split_name: str,
    baseline_module,
    risk_module,
    args,
    model: nn.Module,
    selected_gamma: float,
    thresholds: np.ndarray,
    device: torch.device,
) -> pd.DataFrame:
    dataset = make_dataset(
        baseline_module,
        args,
        split_name,
        training=False,
        repeats=args.test_repeats,
    )

    loader = make_loader(
        dataset,
        args,
        device,
        shuffle=False,
    )

    rows = []

    model.eval()

    with torch.inference_mode():
        for batch in loader:
            truth = batch[
                "target_log"
            ].numpy()

            (
                base_prediction,
                risk_feature,
            ) = (
                risk_module
                .cross_attention_base_context(
                    model.base,
                    batch[
                        "input_waveforms"
                    ].to(
                        device
                    ),
                    batch[
                        "input_features"
                    ].to(
                        device
                    ),
                    batch[
                        "target_features"
                    ].to(
                        device
                    ),
                )
            )

            head = (
                model.head_from_feature(
                    risk_feature
                )
            )

            correction = (
                head[
                    "under_probability"
                ]
                * torch.pow(
                    torch.clamp(
                        head[
                            "tail_probability"
                        ],
                        0.0,
                        1.0,
                    ),
                    selected_gamma,
                )
                * head[
                    "residual"
                ]
            )

            final_prediction = (
                base_prediction
                + correction
            )

            base_np = (
                base_prediction
                .cpu()
                .numpy()
            )

            final_np = (
                final_prediction
                .cpu()
                .numpy()
            )

            tail_probability = (
                head[
                    "tail_probability"
                ]
                .cpu()
                .numpy()
            )

            under_probability = (
                head[
                    "under_probability"
                ]
                .cpu()
                .numpy()
            )

            applied_correction = (
                correction
                .cpu()
                .numpy()
            )

            repeats = batch[
                "repeat"
            ].numpy()

            target_indices = batch[
                "target_station_index"
            ].numpy()

            target_slots = batch[
                "target_slot"
            ].numpy()

            event_ids = list(
                batch[
                    "event_id"
                ]
            )

            for b in range(
                truth.shape[
                    0
                ]
            ):
                for q in range(
                    truth.shape[
                        1
                    ]
                ):
                    true_pga = float(
                        truth[
                            b,
                            q,
                            0,
                        ]
                    )

                    true_pgv = float(
                        truth[
                            b,
                            q,
                            1,
                        ]
                    )

                    rows.append(
                        {
                            "split": (
                                split_name
                            ),
                            "event_id": str(
                                event_ids[
                                    b
                                ]
                            ),
                            "repeat": int(
                                repeats[
                                    b
                                ]
                            ),
                            "target_slot": int(
                                target_slots[
                                    b,
                                    q,
                                ]
                            ),
                            "target_station_index": int(
                                target_indices[
                                    b,
                                    q,
                                ]
                            ),
                            "true_log10_pga": (
                                true_pga
                            ),
                            "true_log10_pgv": (
                                true_pgv
                            ),
                            "base_log10_pga": float(
                                base_np[
                                    b,
                                    q,
                                    0,
                                ]
                            ),
                            "base_log10_pgv": float(
                                base_np[
                                    b,
                                    q,
                                    1,
                                ]
                            ),
                            "final_log10_pga": float(
                                final_np[
                                    b,
                                    q,
                                    0,
                                ]
                            ),
                            "final_log10_pgv": float(
                                final_np[
                                    b,
                                    q,
                                    1,
                                ]
                            ),
                            "tail_probability_pga": float(
                                tail_probability[
                                    b,
                                    q,
                                    0,
                                ]
                            ),
                            "tail_probability_pgv": float(
                                tail_probability[
                                    b,
                                    q,
                                    1,
                                ]
                            ),
                            "under_probability_pga": float(
                                under_probability[
                                    b,
                                    q,
                                    0,
                                ]
                            ),
                            "under_probability_pgv": float(
                                under_probability[
                                    b,
                                    q,
                                    1,
                                ]
                            ),
                            "applied_correction_pga": float(
                                applied_correction[
                                    b,
                                    q,
                                    0,
                                ]
                            ),
                            "applied_correction_pgv": float(
                                applied_correction[
                                    b,
                                    q,
                                    1,
                                ]
                            ),
                            "is_tail_pga": bool(
                                true_pga
                                >= thresholds[
                                    0
                                ]
                            ),
                            "is_tail_pgv": bool(
                                true_pgv
                                >= thresholds[
                                    1
                                ]
                            ),
                            "selected_gamma": float(
                                selected_gamma
                            ),
                        }
                    )

    return pd.DataFrame(
        rows
    )


# ---------------------------------------------------------------------
# Canonical metrics
# ---------------------------------------------------------------------

def bool_array(
    series: pd.Series,
) -> np.ndarray:
    if pd.api.types.is_bool_dtype(
        series
    ):
        return series.to_numpy(
            dtype=bool
        )

    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .isin(
            {
                "true",
                "1",
                "yes",
                "y",
                "t",
            }
        )
        .to_numpy(
            dtype=bool
        )
    )


def element_metric(
    truth: np.ndarray,
    prediction: np.ndarray,
    metric: str,
) -> np.ndarray:
    residual = (
        prediction
        - truth
    )

    absolute = np.abs(
        residual
    )

    if metric == "mae":
        return absolute

    if metric == "bias":
        return residual

    if metric == "factor2":
        return (
            absolute
            <= LOG10_FACTOR_2
        ).astype(
            float
        )

    if metric == "factor3":
        return (
            absolute
            <= LOG10_FACTOR_3
        ).astype(
            float
        )

    if metric == "under05":
        return (
            residual
            <= SEVERE_UNDER_THRESHOLD
        ).astype(
            float
        )

    raise ValueError(
        metric
    )


def event_values(
    frame: pd.DataFrame,
    truth_column: str,
    prediction_column: str,
    metric: str,
) -> pd.Series:
    values = element_metric(
        frame[
            truth_column
        ].to_numpy(
            float
        ),
        frame[
            prediction_column
        ].to_numpy(
            float
        ),
        metric,
    )

    work = frame[
        [
            "event_id",
            "repeat",
        ]
    ].copy()

    work[
        "value"
    ] = values

    event_repeat = (
        work.groupby(
            [
                "event_id",
                "repeat",
            ],
            sort=False,
        )[
            "value"
        ]
        .mean()
        .reset_index()
    )

    return (
        event_repeat.groupby(
            "event_id",
            sort=False,
        )[
            "value"
        ]
        .mean()
    )


def metric_table(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    models = {
        "cross_attention_base": (
            "base"
        ),
        "ca_drg": (
            "final"
        ),
    }

    for (
        split_name,
        split_frame,
    ) in predictions.groupby(
        "split",
        sort=False,
    ):
        for (
            model_name,
            prefix,
        ) in models.items():
            for quantity in (
                "pga",
                "pgv",
            ):
                populations = {
                    "overall": (
                        np.ones(
                            len(
                                split_frame
                            ),
                            dtype=bool,
                        )
                    ),
                    "high_motion_tail": (
                        bool_array(
                            split_frame[
                                f"is_tail_{quantity}"
                            ]
                        )
                    ),
                }

                for (
                    population,
                    mask,
                ) in populations.items():
                    subset = (
                        split_frame.loc[
                            mask
                        ].copy()
                    )

                    if subset.empty:
                        continue

                    for metric in (
                        "mae",
                        "bias",
                        "factor2",
                        "factor3",
                        "under05",
                    ):
                        event_metric = (
                            event_values(
                                subset,
                                f"true_log10_{quantity}",
                                f"{prefix}_log10_{quantity}",
                                metric,
                            )
                        )

                        rows.append(
                            {
                                "split": (
                                    split_name
                                ),
                                "model": (
                                    model_name
                                ),
                                "quantity": (
                                    quantity
                                ),
                                "population": (
                                    population
                                ),
                                "metric": (
                                    metric
                                ),
                                "value": float(
                                    event_metric.mean()
                                ),
                                "n_events": int(
                                    len(
                                        event_metric
                                    )
                                ),
                                "n_target_rows": int(
                                    len(
                                        subset
                                    )
                                ),
                            }
                        )

    return pd.DataFrame(
        rows
    )


def cadrg_minus_base_table(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    for (
        split_name,
        split_frame,
    ) in predictions.groupby(
        "split",
        sort=False,
    ):
        for quantity in (
            "pga",
            "pgv",
        ):
            for population in (
                "overall",
                "high_motion_tail",
            ):
                subset = split_frame

                if (
                    population
                    == "high_motion_tail"
                ):
                    subset = (
                        split_frame.loc[
                            bool_array(
                                split_frame[
                                    f"is_tail_{quantity}"
                                ]
                            )
                        ].copy()
                    )

                if subset.empty:
                    continue

                for metric in (
                    "mae",
                    "bias",
                    "factor2",
                    "under05",
                ):
                    base = event_values(
                        subset,
                        f"true_log10_{quantity}",
                        f"base_log10_{quantity}",
                        metric,
                    )

                    final = event_values(
                        subset,
                        f"true_log10_{quantity}",
                        f"final_log10_{quantity}",
                        metric,
                    )

                    common = (
                        base.index
                        .intersection(
                            final.index
                        )
                    )

                    delta = (
                        final.loc[
                            common
                        ]
                        - base.loc[
                            common
                        ]
                    )

                    base_value = float(
                        base.loc[
                            common
                        ].mean()
                    )

                    final_value = float(
                        final.loc[
                            common
                        ].mean()
                    )

                    record = {
                        "split": (
                            split_name
                        ),
                        "quantity": (
                            quantity
                        ),
                        "population": (
                            population
                        ),
                        "metric": (
                            metric
                        ),
                        "n_paired_events": int(
                            len(
                                common
                            )
                        ),
                        "base_value": (
                            base_value
                        ),
                        "ca_drg_value": (
                            final_value
                        ),
                        "mean_delta_cadrg_minus_base": float(
                            delta.mean()
                        ),
                        "median_delta_cadrg_minus_base": float(
                            delta.median()
                        ),
                    }

                    if metric == "mae":
                        record[
                            "relative_change_percent"
                        ] = float(
                            100.0
                            * (
                                final_value
                                - base_value
                            )
                            / max(
                                abs(
                                    base_value
                                ),
                                1e-12,
                            )
                        )

                    if metric in {
                        "factor2",
                        "under05",
                    }:
                        record[
                            "delta_percentage_points"
                        ] = float(
                            100.0
                            * (
                                final_value
                                - base_value
                            )
                        )

                    rows.append(
                        record
                    )

    return pd.DataFrame(
        rows
    )


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--baseline-module",
        default=(
            "45_phase2_strong_baseline_suite.py"
        ),
    )

    parser.add_argument(
        "--risk-module",
        default=(
            "60_train_cross_attention_dual_risk_joint_selection.py"
        ),
    )

    parser.add_argument(
        "--manifest",
        default=(
            "data/scedc/model_manifests/"
            "scenario_t0_5s_k5_time_clean.csv"
        ),
    )

    parser.add_argument(
        "--h5-root",
        default=(
            "data/scedc/"
            "processed_full_v4/events"
        ),
    )

    parser.add_argument(
        "--split-column",
        default="split_time_clean",
    )

    parser.add_argument(
        "--train-label",
        default="train",
    )

    parser.add_argument(
        "--validation-label",
        default="validation",
    )

    parser.add_argument(
        "--test-label",
        default="test",
    )

    parser.add_argument(
        "--ridgecrest-label",
        default="ridgecrest_ood",
    )

    parser.add_argument(
        "--threshold-json",
        default=(
            "runs/"
            "time_clean_mean_base_t0_5s_k5/"
            "tail_thresholds_q0.90_t0_5s.json"
        ),
        help=(
            "Reuse the TRAIN-only chronological Q90 thresholds "
            "from the existing time-clean pipeline."
        ),
    )

    parser.add_argument(
        "--t0-sec",
        type=int,
        default=5,
    )

    parser.add_argument(
        "--input-stations",
        type=int,
        default=5,
    )

    parser.add_argument(
        "--target-stations",
        type=int,
        default=10,
    )

    parser.add_argument(
        "--input-pre-sec",
        type=float,
        default=2.0,
    )

    parser.add_argument(
        "--hidden-dim",
        type=int,
        default=128,
    )

    parser.add_argument(
        "--attention-heads",
        type=int,
        default=4,
    )

    # Base training
    parser.add_argument(
        "--base-epochs",
        type=int,
        default=50,
    )

    parser.add_argument(
        "--base-validation-repeats",
        type=int,
        default=3,
    )

    parser.add_argument(
        "--base-learning-rate",
        type=float,
        default=1e-3,
    )

    parser.add_argument(
        "--base-weight-decay",
        type=float,
        default=1e-4,
    )

    parser.add_argument(
        "--base-minimum-learning-rate",
        type=float,
        default=1e-5,
    )

    parser.add_argument(
        "--base-lr-patience",
        type=int,
        default=4,
    )

    parser.add_argument(
        "--base-early-stopping-patience",
        type=int,
        default=12,
    )

    parser.add_argument(
        "--base-minimum-delta",
        type=float,
        default=1e-4,
    )

    # Dual-Risk head
    parser.add_argument(
        "--risk-hidden",
        type=int,
        default=64,
    )

    parser.add_argument(
        "--maximum-correction",
        type=float,
        default=1.5,
    )

    parser.add_argument(
        "--head-epochs",
        type=int,
        default=40,
    )

    parser.add_argument(
        "--head-learning-rate",
        type=float,
        default=1e-3,
    )

    parser.add_argument(
        "--head-weight-decay",
        type=float,
        default=1e-4,
    )

    parser.add_argument(
        "--head-monitor-repeats",
        type=int,
        default=3,
    )

    parser.add_argument(
        "--head-selection-repeats",
        type=int,
        default=20,
    )

    parser.add_argument(
        "--prevalence-repeats",
        type=int,
        default=3,
    )

    parser.add_argument(
        "--head-eval-batch-size",
        type=int,
        default=8192,
    )

    parser.add_argument(
        "--lambda-tail-classification",
        type=float,
        default=0.25,
    )

    parser.add_argument(
        "--lambda-under-classification",
        type=float,
        default=0.25,
    )

    parser.add_argument(
        "--lambda-regression",
        type=float,
        default=1.0,
    )

    parser.add_argument(
        "--risk-regression-weight",
        type=float,
        default=2.0,
    )

    parser.add_argument(
        "--lambda-directional",
        type=float,
        default=0.50,
    )

    parser.add_argument(
        "--lambda-leakage",
        type=float,
        default=0.05,
    )

    parser.add_argument(
        "--max-positive-weight",
        type=float,
        default=9.0,
    )

    parser.add_argument(
        "--powers",
        default=(
            "1,1.5,2,2.5,3,4,5,6,7,8,10,12,15,20"
        ),
    )

    parser.add_argument(
        "--overall-budget",
        type=float,
        default=0.005,
    )

    parser.add_argument(
        "--non-tail-budget",
        type=float,
        default=0.003,
    )

    parser.add_argument(
        "--bias-margin",
        type=float,
        default=0.005,
    )

    parser.add_argument(
        "--test-repeats",
        type=int,
        default=20,
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=20260713,
    )

    parser.add_argument(
        "--num-workers",
        type=int,
        default=0,
    )

    parser.add_argument(
        "--device",
        choices=[
            "auto",
            "cpu",
            "cuda",
        ],
        default="auto",
    )

    parser.add_argument(
        "--out-dir",
        default=(
            "runs/"
            "cadrg_chronological_ridgecrest"
        ),
    )

    args = parser.parse_args()

    if args.device == "auto":
        device = torch.device(
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )
    else:
        if (
            args.device
            == "cuda"
            and not torch.cuda.is_available()
        ):
            raise RuntimeError(
                "CUDA requested but unavailable."
            )

        device = torch.device(
            args.device
        )

    set_seed(
        args.seed
    )

    manifest_path = Path(
        args.manifest
    )

    threshold_path = Path(
        args.threshold_json
    )

    if not manifest_path.exists():
        raise FileNotFoundError(
            manifest_path
        )

    if not threshold_path.exists():
        raise FileNotFoundError(
            threshold_path
        )

    baseline_module = load_module(
        args.baseline_module,
        "chronological_cross_attention_module",
    )

    risk_module = load_module(
        args.risk_module,
        "chronological_dual_risk_module",
    )

    threshold_data = json.loads(
        threshold_path.read_text(
            encoding="utf-8"
        )
    )

    thresholds = np.asarray(
        [
            threshold_data[
                "log10_pga_threshold"
            ],
            threshold_data[
                "log10_pgv_threshold"
            ],
        ],
        dtype=np.float32,
    )

    out_dir = Path(
        args.out_dir
    )

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Split audit before model training.
    manifest = pd.read_csv(
        manifest_path,
        dtype={
            "event_id": str,
        },
    )

    split_counts = (
        manifest[
            args.split_column
        ]
        .astype(
            str
        )
        .value_counts()
        .to_dict()
    )

    protocol = {
        **vars(
            args
        ),
        "resolved_device": str(
            device
        ),
        "split_counts_manifest": (
            split_counts
        ),
        "split_definition": {
            "train": "2010-2018",
            "validation": (
                "2019 non-Ridgecrest + 2020"
            ),
            "test": "2021-2024",
            "ridgecrest_ood": (
                "complete held-out 2019 Ridgecrest sequence"
            ),
        },
        "tail_threshold_source": str(
            threshold_path.resolve()
        ),
        "tail_thresholds": {
            "pga": float(
                thresholds[
                    0
                ]
            ),
            "pgv": float(
                thresholds[
                    1
                ]
            ),
        },
        "selection_rule": {
            "overall_delta_max": float(
                args.overall_budget
            ),
            "non_tail_delta_max": float(
                args.non_tail_budget
            ),
            "relative_bias_margin": float(
                args.bias_margin
            ),
            "relative_bias_rule": (
                "|bias_candidate| <= "
                "|bias_base| + margin"
            ),
        },
        "test_accessed_during_selection": False,
        "ridgecrest_accessed_during_selection": False,
        "metric_aggregation": (
            "targets -> repeats -> events"
        ),
    }

    (
        out_dir
        / "run_configuration.json"
    ).write_text(
        json.dumps(
            protocol,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        "=== Step 5: CA-DRG chronological "
        "+ Ridgecrest OOD ==="
    )

    print(
        f"Device                   : "
        f"{device}"
    )

    print(
        f"Manifest split counts    : "
        f"{split_counts}"
    )

    print(
        "Chronological Q90 PGA/PGV: "
        f"{thresholds[0]:.6f}/"
        f"{thresholds[1]:.6f}"
    )

    start_time = time.time()

    # -------------------------------------------------------------
    # 5A Base
    # -------------------------------------------------------------
    base, base_summary = (
        train_chronological_base(
            baseline_module,
            args,
            device,
            out_dir,
        )
    )

    # -------------------------------------------------------------
    # 5B Dual Risk
    # -------------------------------------------------------------
    model, selection = (
        train_and_select_dual_risk(
            baseline_module,
            risk_module,
            args,
            base,
            thresholds,
            device,
            out_dir,
        )
    )

    if model is None:
        summary = {
            "status": (
                "stopped_before_test"
            ),
            "base_summary": (
                base_summary
            ),
            "selection": (
                selection
            ),
            "elapsed_seconds": float(
                time.time()
                - start_time
            ),
            "test_accessed": False,
            "ridgecrest_accessed": False,
        }

        (
            out_dir
            / "run_summary.json"
        ).write_text(
            json.dumps(
                summary,
                indent=2,
            ),
            encoding="utf-8",
        )

        return

    selected_gamma = float(
        selection[
            "selected_gamma"
        ]
    )

    # -------------------------------------------------------------
    # 5C 2021-2024 test
    # -------------------------------------------------------------
    print(
        "\n=== Step 5C: locked 2021-2024 "
        "chronological test ==="
    )

    test_predictions = evaluate_split(
        args.test_label,
        baseline_module,
        risk_module,
        args,
        model,
        selected_gamma,
        thresholds,
        device,
    )

    test_path = (
        out_dir
        / "chronological_test_predictions.csv"
    )

    test_predictions.to_csv(
        test_path,
        index=False,
    )

    # -------------------------------------------------------------
    # 5D Ridgecrest OOD
    # -------------------------------------------------------------
    print(
        "\n=== Step 5D: locked Ridgecrest "
        "sequence-level OOD ==="
    )

    ridgecrest_predictions = (
        evaluate_split(
            args.ridgecrest_label,
            baseline_module,
            risk_module,
            args,
            model,
            selected_gamma,
            thresholds,
            device,
        )
    )

    ridgecrest_path = (
        out_dir
        / "ridgecrest_ood_predictions.csv"
    )

    ridgecrest_predictions.to_csv(
        ridgecrest_path,
        index=False,
    )

    combined = pd.concat(
        [
            test_predictions,
            ridgecrest_predictions,
        ],
        ignore_index=True,
    )

    metrics = metric_table(
        combined
    )

    metrics_path = (
        out_dir
        / "chronological_and_ridgecrest_metrics.csv"
    )

    metrics.to_csv(
        metrics_path,
        index=False,
    )

    deltas = (
        cadrg_minus_base_table(
            combined
        )
    )

    delta_path = (
        out_dir
        / "cadrg_minus_base_chronological_ridgecrest.csv"
    )

    deltas.to_csv(
        delta_path,
        index=False,
    )

    summary = {
        "status": (
            "completed"
        ),
        "elapsed_seconds": float(
            time.time()
            - start_time
        ),
        "base_summary": (
            base_summary
        ),
        "selection": (
            selection
        ),
        "test_events": int(
            test_predictions[
                "event_id"
            ].nunique()
        ),
        "ridgecrest_events": int(
            ridgecrest_predictions[
                "event_id"
            ].nunique()
        ),
        "test_rows": int(
            len(
                test_predictions
            )
        ),
        "ridgecrest_rows": int(
            len(
                ridgecrest_predictions
            )
        ),
        "test_accessed_after_lock": (
            True
        ),
        "ridgecrest_accessed_after_lock": (
            True
        ),
    }

    (
        out_dir
        / "run_summary.json"
    ).write_text(
        json.dumps(
            summary,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        "\n=== Chronological + Ridgecrest "
        "canonical metrics ==="
    )

    print(
        metrics.loc[
            metrics[
                "metric"
            ].isin(
                [
                    "mae",
                    "bias",
                    "factor2",
                    "under05",
                ]
            )
        ][
            [
                "split",
                "model",
                "quantity",
                "population",
                "metric",
                "value",
                "n_events",
                "n_target_rows",
            ]
        ].to_string(
            index=False
        )
    )

    print(
        "\n=== CA-DRG minus Cross-Attention Base ==="
    )

    print(
        deltas.loc[
            deltas[
                "metric"
            ].isin(
                [
                    "mae",
                    "under05",
                ]
            )
        ].to_string(
            index=False
        )
    )

    print(
        "\nOutputs:"
    )

    for path in [
        out_dir
        / "cross_attention_base"
        / "best_model.pt",
        out_dir
        / "dual_risk_head"
        / "selected_dual_risk_head.pt",
        out_dir
        / "dual_risk_head"
        / "selected_epoch_gamma.json",
        test_path,
        ridgecrest_path,
        metrics_path,
        delta_path,
        out_dir
        / "run_summary.json",
    ]:
        print(
            f"  {path.resolve()}"
        )


if __name__ == "__main__":
    main()
