#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fig6_NC_warning_lead_time.py

Nature Communications-style analysis of the physical lead time associated with
CA-URC high-motion predictions under the locked t0=5 s, K=5 protocol.

The script does NOT train a model, select a checkpoint, recalculate a tail
threshold, or resample input/target stations. It merges the locked prediction
rows with precomputed physical lead times and then performs:

  1) target-station lead-time distributions (unique event-station pairs),
  2) latency sensitivity,
  3) event-macro performance by time-to-remaining-peak bin,
  4) paired hierarchical sequence-to-event bootstrap uncertainty,
  5) minimum-lead sensitivity analyses,
  6) publication-ready figures, tables, captions, and a manuscript-number file.

Primary inputs
--------------
Predictions:
  runs/cadrg_gate_ablation_A3_A5/locked_test_ablation_predictions.csv
Physical lead times:
  runs/phase2_warning_lead_time/unique_event_station_lead_times.csv
Manifest:
  data/model_manifests/scenario_t0_5s_k5_linux.csv

The physical lead-time file can be generated by the existing warning lead-time
pipeline (for example, 41_phase2_warning_lead_time_analysis.py). Lead times are
measured from the t0 snapshot, before subtracting any assumed system latency.

Main figure panels
------------------
a) ECDF of time to remaining PGA/PGV peak for high-motion targets
b) Fraction retaining positive net lead after assumed latency
c,d) Tail MAE by time-to-peak bin for PGA and PGV
e,f) Tail U0.5 by time-to-peak bin for PGA and PGV

Supplementary figure
--------------------
Paired tail-MAE change for targets with progressively larger minimum lead time.

Outputs
-------
Fig6_warning_lead_time.png/.pdf/.svg
FigS_minimum_lead_effects.png/.pdf/.svg
Fig6_caption.txt
FigS_caption.txt
TableS5_physical_lead_distribution.csv/.tex
TableS5_latency_sensitivity.csv/.tex
TableS5_metrics_by_peak_lead.csv/.tex
TableS5_minimum_lead_effects.csv/.tex
Section2_5_manuscript_numbers.txt
run_configuration.json

Example (Linux)
---------------
python3 Fig6_NC_warning_lead_time.py \
  --predictions runs/cadrg_gate_ablation_A3_A5/locked_test_ablation_predictions.csv \
  --lead-times runs/phase2_warning_lead_time/unique_event_station_lead_times.csv \
  --manifest data/model_manifests/scenario_t0_5s_k5_linux.csv \
  --sequence-column sequence_group \
  --split-column split_grouped \
  --test-label test \
  --bootstrap-repetitions 10000 \
  --out-dir figures/nc_section_2_5
"""

from __future__ import annotations

import argparse
import json
import math
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


LOG10_FACTOR_2 = math.log10(2.0)
SEVERE_UNDER = -0.5

MODEL_LABELS = {
    "cross_attention": "Cross-Attention Base",
    "ca_urc": "CA-URC",
}

LEAD_BIN_ORDER = ["0–1", "1–2", "2–5", "5–10", "10–20", "≥20"]
DEFAULT_EDGES = [0.0, 1.0, 2.0, 5.0, 10.0, 20.0]

LOCKED_VALUES = {
    ("pga", "overall", "cross_attention", "mae"): 0.305941,
    ("pga", "overall", "ca_urc", "mae"): 0.305531,
    ("pgv", "overall", "cross_attention", "mae"): 0.265767,
    ("pgv", "overall", "ca_urc", "mae"): 0.263486,
    ("pga", "high_motion_tail", "cross_attention", "mae"): 0.639199,
    ("pga", "high_motion_tail", "ca_urc", "mae"): 0.566925,
    ("pgv", "high_motion_tail", "cross_attention", "mae"): 0.746959,
    ("pgv", "high_motion_tail", "ca_urc", "mae"): 0.648410,
}


@dataclass(frozen=True)
class BootstrapResult:
    base: float
    final: float
    delta: float
    base_low: float
    base_high: float
    final_low: float
    final_high: float
    delta_low: float
    delta_high: float
    p_two_sided: float
    probability_final_better: float
    n_events: int
    n_sequence_groups: int
    mode: str


def require_columns(df: pd.DataFrame, columns: Iterable[str], name: str) -> None:
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}")


def parse_bool(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    text = series.astype(str).str.strip().str.lower()
    mapping = {
        "true": True,
        "false": False,
        "1": True,
        "0": False,
        "yes": True,
        "no": False,
        "y": True,
        "n": False,
        "t": True,
        "f": False,
        "nan": False,
        "none": False,
        "": False,
    }
    unknown = sorted(set(text.unique()).difference(mapping))
    if unknown:
        raise ValueError(f"Cannot parse boolean values: {unknown[:20]}")
    return text.map(mapping).astype(bool)


def parse_float_list(text: str) -> list[float]:
    values = [float(item.strip()) for item in str(text).split(",") if item.strip()]
    if not values:
        raise ValueError("Expected at least one numeric value.")
    return values


def make_lead_bins(values: pd.Series, edges: list[float]) -> pd.Categorical:
    edges = sorted(set(float(value) for value in edges))
    if not np.isclose(edges[0], 0.0):
        raise ValueError("Lead-time bin edges must start at 0 s.")
    bins = edges + [np.inf]
    labels: list[str] = []
    for left, right in zip(edges[:-1], edges[1:]):
        labels.append(f"{left:g}–{right:g}")
    labels.append(f"≥{edges[-1]:g}")
    return pd.cut(
        pd.to_numeric(values, errors="coerce"),
        bins=bins,
        labels=labels,
        right=False,
        include_lowest=True,
        ordered=True,
    )


def load_and_merge(
    predictions_path: Path,
    lead_times_path: Path,
    manifest_path: Path,
    split_column: str,
    test_label: str,
    sequence_column: str,
) -> tuple[pd.DataFrame, dict[str, object]]:
    for path in (predictions_path, lead_times_path, manifest_path):
        if not path.exists():
            raise FileNotFoundError(path)

    pred = pd.read_csv(predictions_path, dtype={"event_id": str})
    lead = pd.read_csv(lead_times_path, dtype={"event_id": str})
    manifest = pd.read_csv(manifest_path, dtype={"event_id": str})

    pred_required = [
        "event_id",
        "repeat",
        "target_station_index",
        "true_log10_pga",
        "true_log10_pgv",
        "is_tail_pga",
        "is_tail_pgv",
        "A2_cross_attention_base_log10_pga",
        "A2_cross_attention_base_log10_pgv",
        "A4_under_only_log10_pga",
        "A4_under_only_log10_pgv",
    ]
    lead_required = [
        "event_id",
        "target_station_index",
        "lead_to_pga_peak_sec",
        "lead_to_pgv_peak_sec",
        "pga_highmotion_crossing_lead_sec",
        "pgv_highmotion_crossing_lead_sec",
        "true_log10_pga_recomputed",
        "true_log10_pgv_recomputed",
        "pga_peak_near_window_end",
        "pgv_peak_near_window_end",
    ]
    require_columns(pred, pred_required, "prediction file")
    require_columns(lead, lead_required, "physical lead-time file")
    require_columns(
        manifest,
        ["event_id", split_column, sequence_column],
        "scenario manifest",
    )

    pred["event_id"] = pred["event_id"].astype(str).str.strip()
    lead["event_id"] = lead["event_id"].astype(str).str.strip()
    manifest["event_id"] = manifest["event_id"].astype(str).str.strip()

    pred["is_tail_pga"] = parse_bool(pred["is_tail_pga"])
    pred["is_tail_pgv"] = parse_bool(pred["is_tail_pgv"])
    lead["pga_peak_near_window_end"] = parse_bool(lead["pga_peak_near_window_end"])
    lead["pgv_peak_near_window_end"] = parse_bool(lead["pgv_peak_near_window_end"])

    prediction_keys = ["event_id", "repeat", "target_station_index"]
    if pred.duplicated(prediction_keys).any():
        raise RuntimeError(f"Prediction rows are not unique on {prediction_keys}.")

    lead_keys = ["event_id", "target_station_index"]
    if lead.duplicated(lead_keys).any():
        raise RuntimeError(f"Physical lead-time rows are not unique on {lead_keys}.")

    test_manifest = manifest.loc[
        manifest[split_column].astype(str).eq(str(test_label)),
        ["event_id", sequence_column],
    ].copy()
    if test_manifest["event_id"].duplicated().any():
        raise RuntimeError("The test manifest contains duplicate event IDs.")
    test_manifest = test_manifest.rename(columns={sequence_column: "sequence_group"})

    merged = pred.merge(lead, on=lead_keys, how="left", validate="many_to_one")
    merged = merged.merge(
        test_manifest,
        on="event_id",
        how="left",
        validate="many_to_one",
    )

    if merged["lead_to_pga_peak_sec"].isna().all():
        raise RuntimeError("No PGA lead times were merged.")
    if merged["lead_to_pgv_peak_sec"].isna().all():
        raise RuntimeError("No PGV lead times were merged.")
    if merged["sequence_group"].isna().any():
        missing = merged.loc[merged["sequence_group"].isna(), "event_id"].unique()[:20]
        raise RuntimeError(f"Missing sequence groups for test events: {missing.tolist()}")

    merged["cross_attention_log10_pga"] = pd.to_numeric(
        merged["A2_cross_attention_base_log10_pga"], errors="coerce"
    )
    merged["cross_attention_log10_pgv"] = pd.to_numeric(
        merged["A2_cross_attention_base_log10_pgv"], errors="coerce"
    )
    merged["ca_urc_log10_pga"] = pd.to_numeric(
        merged["A4_under_only_log10_pga"], errors="coerce"
    )
    merged["ca_urc_log10_pgv"] = pd.to_numeric(
        merged["A4_under_only_log10_pgv"], errors="coerce"
    )

    pga_truth_diff = np.abs(
        pd.to_numeric(merged["true_log10_pga"], errors="coerce").to_numpy(float)
        - pd.to_numeric(merged["true_log10_pga_recomputed"], errors="coerce").to_numpy(float)
    )
    pgv_truth_diff = np.abs(
        pd.to_numeric(merged["true_log10_pgv"], errors="coerce").to_numpy(float)
        - pd.to_numeric(merged["true_log10_pgv_recomputed"], errors="coerce").to_numpy(float)
    )

    audit = {
        "prediction_rows": int(len(pred)),
        "merged_rows": int(len(merged)),
        "events": int(merged["event_id"].nunique()),
        "sequence_groups": int(merged["sequence_group"].nunique()),
        "unique_event_station_pairs": int(
            merged[["event_id", "target_station_index"]].drop_duplicates().shape[0]
        ),
        "pga_tail_rows": int(merged["is_tail_pga"].sum()),
        "pgv_tail_rows": int(merged["is_tail_pgv"].sum()),
        "pga_tail_events": int(merged.loc[merged["is_tail_pga"], "event_id"].nunique()),
        "pgv_tail_events": int(merged.loc[merged["is_tail_pgv"], "event_id"].nunique()),
        "max_abs_truth_diff_pga": float(np.nanmax(pga_truth_diff)),
        "max_abs_truth_diff_pgv": float(np.nanmax(pgv_truth_diff)),
    }
    if audit["max_abs_truth_diff_pga"] > 1e-5 or audit["max_abs_truth_diff_pgv"] > 1e-5:
        raise RuntimeError(f"Prediction/physical truth audit failed: {audit}")

    return merged, audit


def metric_element(truth: np.ndarray, prediction: np.ndarray, metric: str) -> np.ndarray:
    residual = prediction - truth
    if metric == "mae":
        return np.abs(residual)
    if metric == "bias":
        return residual
    if metric == "under05":
        return (residual <= SEVERE_UNDER).astype(float)
    if metric == "factor2":
        return (np.abs(residual) <= LOG10_FACTOR_2).astype(float)
    raise ValueError(metric)


def event_metric_series(
    frame: pd.DataFrame,
    quantity: str,
    model: str,
    metric: str,
) -> pd.Series:
    if frame.empty:
        return pd.Series(dtype=float)
    truth = pd.to_numeric(frame[f"true_log10_{quantity}"], errors="coerce").to_numpy(float)
    pred = pd.to_numeric(frame[f"{model}_log10_{quantity}"], errors="coerce").to_numpy(float)
    values = metric_element(truth, pred, metric)
    work = frame[["event_id", "repeat"]].copy()
    work["value"] = values
    event_repeat = (
        work.groupby(["event_id", "repeat"], sort=False)["value"]
        .mean()
        .reset_index()
    )
    return event_repeat.groupby("event_id", sort=False)["value"].mean()


def locked_metric_audit(frame: pd.DataFrame, tolerance: float = 5e-5) -> None:
    failures: list[str] = []
    for (quantity, population, model, metric), expected in LOCKED_VALUES.items():
        subset = frame if population == "overall" else frame.loc[frame[f"is_tail_{quantity}"]]
        value = float(event_metric_series(subset, quantity, model, metric).mean())
        if not np.isclose(value, expected, atol=tolerance, rtol=0.0):
            failures.append(
                f"{quantity}/{population}/{model}/{metric}: observed={value:.6f}, expected={expected:.6f}"
            )
    if failures:
        raise RuntimeError("Locked prediction audit failed:\n  " + "\n  ".join(failures))


def two_sided_sign_p(distribution: np.ndarray) -> float:
    finite = distribution[np.isfinite(distribution)]
    if finite.size == 0:
        return float("nan")
    lower = (np.sum(finite <= 0.0) + 1.0) / (finite.size + 1.0)
    upper = (np.sum(finite >= 0.0) + 1.0) / (finite.size + 1.0)
    return float(min(1.0, 2.0 * min(lower, upper)))


def bootstrap_paired_event_table(
    event_table: pd.DataFrame,
    repetitions: int,
    confidence: float,
    seed: int,
) -> BootstrapResult:
    require_columns(event_table, ["event_id", "sequence_group", "base", "final"], "event table")
    event_table = event_table.dropna(subset=["base", "final", "sequence_group"]).copy()
    event_table["delta"] = event_table["final"] - event_table["base"]
    n_events = int(len(event_table))
    sequence_names = event_table["sequence_group"].astype(str).unique().tolist()
    n_groups = len(sequence_names)
    if n_events < 2:
        return BootstrapResult(
            base=float(event_table["base"].mean()),
            final=float(event_table["final"].mean()),
            delta=float(event_table["delta"].mean()),
            base_low=float("nan"), base_high=float("nan"),
            final_low=float("nan"), final_high=float("nan"),
            delta_low=float("nan"), delta_high=float("nan"),
            p_two_sided=float("nan"), probability_final_better=float("nan"),
            n_events=n_events, n_sequence_groups=n_groups, mode="insufficient",
        )

    group_indices = [
        np.flatnonzero(event_table["sequence_group"].astype(str).to_numpy() == group)
        for group in sequence_names
    ]
    base_values = event_table["base"].to_numpy(float)
    final_values = event_table["final"].to_numpy(float)
    delta_values = event_table["delta"].to_numpy(float)
    rng = np.random.default_rng(seed)
    boot_base = np.empty(repetitions, dtype=float)
    boot_final = np.empty(repetitions, dtype=float)
    boot_delta = np.empty(repetitions, dtype=float)

    if n_groups >= 2:
        mode = "hierarchical_sequence_event"
        for b in range(repetitions):
            selected_group_positions = rng.integers(0, n_groups, size=n_groups)
            sampled_indices: list[np.ndarray] = []
            for group_position in selected_group_positions:
                idx = group_indices[int(group_position)]
                sampled_indices.append(rng.choice(idx, size=len(idx), replace=True))
            sample = np.concatenate(sampled_indices)
            boot_base[b] = float(base_values[sample].mean())
            boot_final[b] = float(final_values[sample].mean())
            boot_delta[b] = float(delta_values[sample].mean())
    else:
        mode = "event_only_fallback"
        warnings.warn(
            "Only one sequence group contributes to a lead-time subset; "
            "using event-only bootstrap for that subset.",
            RuntimeWarning,
        )
        for b in range(repetitions):
            sample = rng.integers(0, n_events, size=n_events)
            boot_base[b] = float(base_values[sample].mean())
            boot_final[b] = float(final_values[sample].mean())
            boot_delta[b] = float(delta_values[sample].mean())

    alpha = (1.0 - confidence) / 2.0
    q_low, q_high = [100.0 * alpha, 100.0 * (1.0 - alpha)]
    return BootstrapResult(
        base=float(base_values.mean()),
        final=float(final_values.mean()),
        delta=float(delta_values.mean()),
        base_low=float(np.percentile(boot_base, q_low)),
        base_high=float(np.percentile(boot_base, q_high)),
        final_low=float(np.percentile(boot_final, q_low)),
        final_high=float(np.percentile(boot_final, q_high)),
        delta_low=float(np.percentile(boot_delta, q_low)),
        delta_high=float(np.percentile(boot_delta, q_high)),
        p_two_sided=two_sided_sign_p(boot_delta),
        probability_final_better=float(np.mean(boot_delta < 0.0)),
        n_events=n_events,
        n_sequence_groups=n_groups,
        mode=mode,
    )


def event_table_for_subset(
    frame: pd.DataFrame,
    quantity: str,
    metric: str,
) -> pd.DataFrame:
    base = event_metric_series(frame, quantity, "cross_attention", metric)
    final = event_metric_series(frame, quantity, "ca_urc", metric)
    common = base.index.intersection(final.index)
    groups = (
        frame[["event_id", "sequence_group"]]
        .drop_duplicates("event_id")
        .set_index("event_id")["sequence_group"]
    )
    return pd.DataFrame(
        {
            "event_id": common.astype(str),
            "sequence_group": groups.loc[common].astype(str).to_numpy(),
            "base": base.loc[common].to_numpy(float),
            "final": final.loc[common].to_numpy(float),
        }
    )


def unique_physical_pairs(frame: pd.DataFrame) -> pd.DataFrame:
    keys = ["event_id", "target_station_index"]
    consistency_columns = [
        "true_log10_pga",
        "true_log10_pgv",
        "is_tail_pga",
        "is_tail_pgv",
        "lead_to_pga_peak_sec",
        "lead_to_pgv_peak_sec",
        "pga_highmotion_crossing_lead_sec",
        "pgv_highmotion_crossing_lead_sec",
    ]
    for column in consistency_columns:
        counts = frame.groupby(keys, sort=False)[column].nunique(dropna=False)
        if (counts > 1).any():
            raise RuntimeError(
                f"Physical quantity {column!r} is inconsistent across repeats for the same event-station pair."
            )
    keep = keys + consistency_columns + [
        "sequence_group",
        "pga_peak_near_window_end",
        "pgv_peak_near_window_end",
    ]
    return frame[keep].drop_duplicates(keys).reset_index(drop=True)


def lead_distribution_table(unique_pairs: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for quantity in ("pga", "pgv"):
        tail = unique_pairs.loc[unique_pairs[f"is_tail_{quantity}"]].copy()
        definitions = {
            "time_to_remaining_peak": f"lead_to_{quantity}_peak_sec",
            "time_to_highmotion_threshold_crossing": f"{quantity}_highmotion_crossing_lead_sec",
        }
        for definition, column in definitions.items():
            values = pd.to_numeric(tail[column], errors="coerce").to_numpy(float)
            values = values[np.isfinite(values)]
            if values.size == 0:
                continue
            rows.append(
                {
                    "quantity": quantity,
                    "lead_definition": definition,
                    "n_unique_event_station_pairs_total": int(len(tail)),
                    "n_with_finite_lead": int(values.size),
                    "finite_fraction": float(values.size / max(len(tail), 1)),
                    "median_sec": float(np.median(values)),
                    "p25_sec": float(np.percentile(values, 25)),
                    "p75_sec": float(np.percentile(values, 75)),
                    "p90_sec": float(np.percentile(values, 90)),
                    "fraction_gt_0s": float(np.mean(values > 0.0)),
                    "fraction_ge_1s": float(np.mean(values >= 1.0)),
                    "fraction_ge_2s": float(np.mean(values >= 2.0)),
                    "fraction_ge_5s": float(np.mean(values >= 5.0)),
                    "fraction_ge_10s": float(np.mean(values >= 10.0)),
                }
            )
    return pd.DataFrame(rows)


def latency_sensitivity_table(
    unique_pairs: pd.DataFrame,
    latencies: list[float],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for quantity in ("pga", "pgv"):
        tail = unique_pairs.loc[unique_pairs[f"is_tail_{quantity}"]].copy()
        definitions = {
            "time_to_remaining_peak": f"lead_to_{quantity}_peak_sec",
            "time_to_highmotion_threshold_crossing": f"{quantity}_highmotion_crossing_lead_sec",
        }
        for definition, column in definitions.items():
            raw = pd.to_numeric(tail[column], errors="coerce").to_numpy(float)
            raw = raw[np.isfinite(raw)]
            if raw.size == 0:
                continue
            for latency in latencies:
                net = raw - float(latency)
                rows.append(
                    {
                        "quantity": quantity,
                        "lead_definition": definition,
                        "assumed_total_latency_sec": float(latency),
                        "n_with_defined_lead": int(raw.size),
                        "fraction_positive_net_lead": float(np.mean(net > 0.0)),
                        "fraction_net_lead_ge_1s": float(np.mean(net >= 1.0)),
                        "fraction_net_lead_ge_2s": float(np.mean(net >= 2.0)),
                        "fraction_net_lead_ge_5s": float(np.mean(net >= 5.0)),
                        "median_net_lead_sec": float(np.median(net)),
                    }
                )
    return pd.DataFrame(rows)


def metrics_by_peak_lead(
    frame: pd.DataFrame,
    edges: list[float],
    repetitions: int,
    confidence: float,
    seed: int,
    minimum_events: int,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for quantity_index, quantity in enumerate(("pga", "pgv")):
        lead_column = f"lead_to_{quantity}_peak_sec"
        bin_column = f"{quantity}_peak_lead_bin"
        work = frame.loc[frame[f"is_tail_{quantity}"]].copy()
        work[bin_column] = make_lead_bins(work[lead_column], edges)
        for bin_index, (lead_bin, subset) in enumerate(
            work.groupby(bin_column, observed=True, sort=False)
        ):
            for metric_index, metric in enumerate(("mae", "under05", "bias", "factor2")):
                event_table = event_table_for_subset(subset, quantity, metric)
                result = bootstrap_paired_event_table(
                    event_table,
                    repetitions=repetitions,
                    confidence=confidence,
                    seed=seed + 1000 * quantity_index + 100 * bin_index + metric_index,
                )
                rows.append(
                    {
                        "quantity": quantity,
                        "lead_bin": str(lead_bin),
                        "median_lead_sec": float(pd.to_numeric(subset[lead_column], errors="coerce").median()),
                        "metric": metric,
                        "cross_attention_value": result.base,
                        "cross_attention_ci_lower": result.base_low,
                        "cross_attention_ci_upper": result.base_high,
                        "ca_urc_value": result.final,
                        "ca_urc_ci_lower": result.final_low,
                        "ca_urc_ci_upper": result.final_high,
                        "delta_caurc_minus_base": result.delta,
                        "delta_ci_lower": result.delta_low,
                        "delta_ci_upper": result.delta_high,
                        "relative_change_percent": (
                            100.0 * result.delta / abs(result.base)
                            if metric == "mae" and abs(result.base) > 1e-12
                            else np.nan
                        ),
                        "delta_percentage_points": (
                            100.0 * result.delta
                            if metric in {"under05", "factor2"}
                            else np.nan
                        ),
                        "bootstrap_p_two_sided": result.p_two_sided,
                        "bootstrap_probability_caurc_better": result.probability_final_better,
                        "n_events": result.n_events,
                        "n_sequence_groups": result.n_sequence_groups,
                        "n_target_rows": int(len(subset)),
                        "bootstrap_mode": result.mode,
                        "display_eligible": bool(result.n_events >= minimum_events),
                    }
                )
    return pd.DataFrame(rows)


def minimum_lead_effects(
    frame: pd.DataFrame,
    minimum_leads: list[float],
    repetitions: int,
    confidence: float,
    seed: int,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for quantity_index, quantity in enumerate(("pga", "pgv")):
        lead_column = f"lead_to_{quantity}_peak_sec"
        tail = frame.loc[frame[f"is_tail_{quantity}"]].copy()
        for threshold_index, minimum_lead in enumerate(minimum_leads):
            if np.isclose(minimum_lead, 0.0):
                subset = tail.loc[pd.to_numeric(tail[lead_column], errors="coerce") > 0.0].copy()
                threshold_label = ">0"
            else:
                subset = tail.loc[
                    pd.to_numeric(tail[lead_column], errors="coerce") >= float(minimum_lead)
                ].copy()
                threshold_label = f"≥{minimum_lead:g}"
            for metric_index, metric in enumerate(("mae", "under05")):
                event_table = event_table_for_subset(subset, quantity, metric)
                result = bootstrap_paired_event_table(
                    event_table,
                    repetitions=repetitions,
                    confidence=confidence,
                    seed=seed + 5000 + 1000 * quantity_index + 100 * threshold_index + metric_index,
                )
                rows.append(
                    {
                        "quantity": quantity,
                        "minimum_peak_lead_sec": float(minimum_lead),
                        "minimum_peak_lead_label": threshold_label,
                        "metric": metric,
                        "cross_attention_value": result.base,
                        "ca_urc_value": result.final,
                        "delta_caurc_minus_base": result.delta,
                        "delta_ci_lower": result.delta_low,
                        "delta_ci_upper": result.delta_high,
                        "relative_change_percent": (
                            100.0 * result.delta / abs(result.base)
                            if metric == "mae" and abs(result.base) > 1e-12
                            else np.nan
                        ),
                        "delta_percentage_points": (
                            100.0 * result.delta if metric == "under05" else np.nan
                        ),
                        "bootstrap_p_two_sided": result.p_two_sided,
                        "bootstrap_probability_caurc_better": result.probability_final_better,
                        "n_events": result.n_events,
                        "n_sequence_groups": result.n_sequence_groups,
                        "n_target_rows": int(len(subset)),
                        "bootstrap_mode": result.mode,
                    }
                )
    return pd.DataFrame(rows)


def style_axis(ax: plt.Axes, grid_axis: str = "both") -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_axisbelow(True)
    if grid_axis == "x":
        ax.grid(axis="x", linewidth=0.45, alpha=0.24)
    elif grid_axis == "y":
        ax.grid(axis="y", linewidth=0.45, alpha=0.24)
    elif grid_axis == "both":
        ax.grid(linewidth=0.45, alpha=0.20)


def add_panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(
        -0.14,
        1.05,
        label,
        transform=ax.transAxes,
        fontsize=9.0,
        fontweight="bold",
        va="bottom",
        ha="left",
    )


def plot_ecdf_panel(ax: plt.Axes, unique_pairs: pd.DataFrame) -> None:
    for quantity in ("pga", "pgv"):
        subset = unique_pairs.loc[unique_pairs[f"is_tail_{quantity}"]]
        values = pd.to_numeric(
            subset[f"lead_to_{quantity}_peak_sec"], errors="coerce"
        ).to_numpy(float)
        values = np.sort(values[np.isfinite(values)])
        if values.size == 0:
            continue
        y = np.arange(1, values.size + 1, dtype=float) / values.size
        ax.step(values, y, where="post", linewidth=1.55, label=quantity.upper())
    for reference in (2.0, 5.0, 10.0):
        ax.axvline(reference, linestyle=":", linewidth=0.75, alpha=0.55)
    ax.set_xlabel("Time to remaining peak after the 5-s snapshot (s)")
    ax.set_ylabel("Cumulative fraction")
    ax.set_ylim(0.0, 1.0)
    ax.legend(frameon=False, loc="lower right")
    ax.set_title("Many high-motion peaks remain after the 5-s snapshot", loc="left", fontweight="bold", fontsize=7.8)
    style_axis(ax)


def plot_latency_panel(ax: plt.Axes, latency: pd.DataFrame) -> None:
    for quantity in ("pga", "pgv"):
        for definition, linestyle, suffix in (
            ("time_to_remaining_peak", "-", "peak"),
            ("time_to_highmotion_threshold_crossing", "--", "threshold crossing"),
        ):
            subset = latency.loc[
                latency["quantity"].eq(quantity)
                & latency["lead_definition"].eq(definition)
            ].sort_values("assumed_total_latency_sec")
            if subset.empty:
                continue
            ax.plot(
                subset["assumed_total_latency_sec"],
                100.0 * subset["fraction_positive_net_lead"],
                marker="o" if definition == "time_to_remaining_peak" else "s",
                linestyle=linestyle,
                linewidth=1.35,
                markersize=3.6,
                label=f"{quantity.upper()} to {suffix}",
            )
    ax.set_xlabel("Assumed total system latency (s)")
    ax.set_ylabel("Targets with positive net lead (%)")
    ax.set_ylim(0.0, 102.0)
    ax.legend(frameon=False, fontsize=6.4, ncol=2, loc="lower left")
    ax.set_title("System latency reduces positive warning lead", loc="left", fontweight="bold", fontsize=7.8)
    style_axis(ax)


def plot_metric_by_bin(
    ax: plt.Axes,
    metrics: pd.DataFrame,
    quantity: str,
    metric: str,
    title: str,
    ylabel: str,
    percent: bool = False,
) -> None:
    subset = metrics.loc[
        metrics["quantity"].eq(quantity)
        & metrics["metric"].eq(metric)
        & metrics["display_eligible"]
    ].copy()
    order = [label for label in LEAD_BIN_ORDER if label in set(subset["lead_bin"])]
    x = np.arange(len(order), dtype=float)
    offsets = {"cross_attention": -0.08, "ca_urc": 0.08}
    for model in ("cross_attention", "ca_urc"):
        values: list[float] = []
        lows: list[float] = []
        highs: list[float] = []
        for lead_bin in order:
            row = subset.loc[subset["lead_bin"].eq(lead_bin)]
            if len(row) != 1:
                values.append(np.nan)
                lows.append(np.nan)
                highs.append(np.nan)
                continue
            record = row.iloc[0]
            value = float(record[f"{model}_value"])
            low = float(record[f"{model}_ci_lower"])
            high = float(record[f"{model}_ci_upper"])
            if percent:
                value *= 100.0
                low *= 100.0
                high *= 100.0
            values.append(value)
            lows.append(low)
            highs.append(high)
        values_array = np.asarray(values, dtype=float)
        low_array = np.asarray(lows, dtype=float)
        high_array = np.asarray(highs, dtype=float)
        yerr = np.vstack([values_array - low_array, high_array - values_array])
        ax.errorbar(
            x + offsets[model],
            values_array,
            yerr=yerr,
            marker="o" if model == "cross_attention" else "s",
            linewidth=1.25,
            markersize=3.6,
            capsize=2.2,
            label=MODEL_LABELS[model],
        )
    ax.set_xticks(x)
    ax.set_xticklabels([f"{label}\ns" for label in order])
    ax.set_xlabel("Time to remaining peak")
    ax.set_ylabel(ylabel)
    ax.set_title(title, loc="left", fontweight="bold", fontsize=7.8)
    style_axis(ax, grid_axis="y")

    # Event counts are identical for the two paired models.
    counts = []
    for lead_bin in order:
        row = subset.loc[subset["lead_bin"].eq(lead_bin)]
        counts.append(int(row.iloc[0]["n_events"]) if len(row) == 1 else 0)
    ymin, ymax = ax.get_ylim()
    ax.set_ylim(ymin, ymax + 0.04 * max(ymax - ymin, 1e-6))
    for xx, count in zip(x, counts):
        ax.text(
            xx,
            0.985,
            f"n={count}",
            transform=ax.get_xaxis_transform(),
            ha="center",
            va="top",
            fontsize=5.9,
        )


def plot_main_figure(
    unique_pairs: pd.DataFrame,
    latency: pd.DataFrame,
    metrics: pd.DataFrame,
    out_dir: Path,
    dpi: int,
) -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 7.2,
            "axes.titlesize": 8.0,
            "axes.labelsize": 7.3,
            "xtick.labelsize": 6.5,
            "ytick.labelsize": 6.5,
            "legend.fontsize": 6.7,
            "axes.linewidth": 0.65,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
        }
    )
    width = 183.0 / 25.4
    height = 160.0 / 25.4
    fig, axes = plt.subplots(3, 2, figsize=(width, height))

    plot_ecdf_panel(axes[0, 0], unique_pairs)
    plot_latency_panel(axes[0, 1], latency)
    plot_metric_by_bin(
        axes[1, 0], metrics, "pga", "mae",
        "PGA tail MAE by lead time",
        r"High-motion-tail MAE ($\log_{10}$ units)",
    )
    plot_metric_by_bin(
        axes[1, 1], metrics, "pgv", "mae",
        "PGV tail MAE by lead time",
        r"High-motion-tail MAE ($\log_{10}$ units)",
    )
    plot_metric_by_bin(
        axes[2, 0], metrics, "pga", "under05",
        "PGA tail underprediction by lead time",
        r"High-motion-tail $U_{0.5}$ (%)",
        percent=True,
    )
    plot_metric_by_bin(
        axes[2, 1], metrics, "pgv", "under05",
        "PGV tail underprediction by lead time",
        r"High-motion-tail $U_{0.5}$ (%)",
        percent=True,
    )

    for ax, label in zip(axes.ravel(), list("abcdef")):
        add_panel_label(ax, label)

    handles, labels = axes[1, 0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="upper center",
        bbox_to_anchor=(0.5, 0.998),
        ncol=2,
        frameon=False,
        columnspacing=1.4,
        handletextpad=0.5,
    )
    for ax in (axes[1, 0], axes[1, 1], axes[2, 0], axes[2, 1]):
        legend = ax.get_legend()
        if legend is not None:
            legend.remove()

    fig.subplots_adjust(
        left=0.085,
        right=0.992,
        bottom=0.080,
        top=0.945,
        wspace=0.32,
        hspace=0.50,
    )

    for suffix in ("png", "pdf", "svg"):
        path = out_dir / f"Fig6_warning_lead_time.{suffix}"
        kwargs = {"bbox_inches": "tight", "facecolor": "white"}
        if suffix == "png":
            kwargs["dpi"] = dpi
        fig.savefig(path, **kwargs)
    plt.close(fig)


def plot_minimum_lead_figure(
    effects: pd.DataFrame,
    out_dir: Path,
    dpi: int,
) -> None:
    width = 183.0 / 25.4
    height = 68.0 / 25.4
    fig, axes = plt.subplots(1, 2, figsize=(width, height))
    for ax, quantity, panel in zip(axes, ("pga", "pgv"), ("a", "b")):
        subset = effects.loc[
            effects["quantity"].eq(quantity) & effects["metric"].eq("mae")
        ].sort_values("minimum_peak_lead_sec")
        x_values = subset["minimum_peak_lead_sec"].to_numpy(float)
        x = np.arange(len(subset), dtype=float)
        delta = subset["delta_caurc_minus_base"].to_numpy(float)
        low = subset["delta_ci_lower"].to_numpy(float)
        high = subset["delta_ci_upper"].to_numpy(float)
        ax.axhline(0.0, linewidth=0.75, alpha=0.55)
        ax.errorbar(
            x,
            delta,
            yerr=np.vstack([delta - low, high - delta]),
            marker="o",
            linewidth=1.25,
            capsize=2.4,
        )
        ax.set_xticks(x)
        labels = subset["minimum_peak_lead_label"].astype(str).tolist()
        ax.set_xticklabels([f"{label} s" for label in labels])
        ax.set_xlabel("Minimum time to remaining peak")
        ax.set_ylabel(r"Paired tail-MAE change ($\log_{10}$ units)")
        ax.set_title(
            f"{quantity.upper()}: CA-URC benefit at positive lead times",
            loc="left",
            fontweight="bold",
        )
        style_axis(ax, grid_axis="y")
        add_panel_label(ax, panel)
        for xx, yy, n in zip(x, delta, subset["n_events"].astype(int)):
            ax.text(xx, yy, f"n={n}", fontsize=5.8, va="bottom", ha="center")
    fig.subplots_adjust(left=0.09, right=0.99, bottom=0.22, top=0.86, wspace=0.35)
    for suffix in ("png", "pdf", "svg"):
        path = out_dir / f"FigS_minimum_lead_effects.{suffix}"
        kwargs = {"bbox_inches": "tight", "facecolor": "white"}
        if suffix == "png":
            kwargs["dpi"] = dpi
        fig.savefig(path, **kwargs)
    plt.close(fig)


def dataframe_to_latex(frame: pd.DataFrame, percent_columns: set[str] | None = None) -> str:
    display = frame.copy()
    percent_columns = percent_columns or set()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            if column in percent_columns or column.startswith("fraction_"):
                display[column] = display[column].map(
                    lambda value: "--" if pd.isna(value) else f"{100.0 * value:.1f}\\%"
                )
            else:
                display[column] = display[column].map(
                    lambda value: "--" if pd.isna(value) else f"{value:.3f}"
                )
    return display.to_latex(index=False, escape=False)


def get_row(
    frame: pd.DataFrame,
    quantity: str,
    definition: str,
) -> pd.Series | None:
    subset = frame.loc[
        frame["quantity"].eq(quantity) & frame["lead_definition"].eq(definition)
    ]
    if len(subset) != 1:
        return None
    return subset.iloc[0]


def effect_row(
    effects: pd.DataFrame,
    quantity: str,
    minimum_lead: float,
    metric: str,
) -> pd.Series | None:
    subset = effects.loc[
        effects["quantity"].eq(quantity)
        & np.isclose(effects["minimum_peak_lead_sec"], minimum_lead)
        & effects["metric"].eq(metric)
    ]
    if len(subset) != 1:
        return None
    return subset.iloc[0]


def write_manuscript_numbers(
    distribution: pd.DataFrame,
    latency: pd.DataFrame,
    effects: pd.DataFrame,
    audit: dict[str, object],
    out_path: Path,
) -> None:
    lines: list[str] = []
    lines.append("SECTION 2.5 MANUSCRIPT NUMBERS (generated from locked files)")
    lines.append("=" * 72)
    lines.append(
        f"Locked sample: {audit['events']} events; {audit['sequence_groups']} sequence groups; "
        f"{audit['prediction_rows']:,} prediction rows; "
        f"{audit['unique_event_station_pairs']:,} unique event-station pairs."
    )
    lines.append("")

    for quantity in ("pga", "pgv"):
        peak = get_row(distribution, quantity, "time_to_remaining_peak")
        crossing = get_row(distribution, quantity, "time_to_highmotion_threshold_crossing")
        if peak is not None:
            lines.append(
                f"{quantity.upper()} time to remaining peak: median={peak['median_sec']:.2f} s, "
                f"IQR={peak['p25_sec']:.2f}-{peak['p75_sec']:.2f} s, "
                f">0 s={100*peak['fraction_gt_0s']:.1f}%, "
                f">=2 s={100*peak['fraction_ge_2s']:.1f}%, "
                f">=5 s={100*peak['fraction_ge_5s']:.1f}%, "
                f">=10 s={100*peak['fraction_ge_10s']:.1f}%."
            )
        if crossing is not None:
            lines.append(
                f"{quantity.upper()} time to high-motion threshold crossing: "
                f"median={crossing['median_sec']:.2f} s, "
                f"IQR={crossing['p25_sec']:.2f}-{crossing['p75_sec']:.2f} s, "
                f">0 s={100*crossing['fraction_gt_0s']:.1f}%."
            )

        for minimum in (0.0, 2.0, 5.0):
            row = effect_row(effects, quantity, minimum, "mae")
            if row is not None:
                relation = "excluded zero" if row["delta_ci_upper"] < 0 or row["delta_ci_lower"] > 0 else "included zero"
                label = ">0" if np.isclose(minimum, 0.0) else f">={minimum:g}"
                lines.append(
                    f"{quantity.upper()} tail MAE for peak lead {label} s: "
                    f"Base={row['cross_attention_value']:.3f}, CA-URC={row['ca_urc_value']:.3f}, "
                    f"delta={row['delta_caurc_minus_base']:+.3f}, "
                    f"95% CI=[{row['delta_ci_lower']:+.3f}, {row['delta_ci_upper']:+.3f}] "
                    f"({relation}); n={int(row['n_events'])} events."
                )
        lines.append("")

    for assumed_latency in (1.0, 2.0):
        lines.append(f"Assumed total latency = {assumed_latency:g} s")
        for quantity in ("pga", "pgv"):
            for definition in (
                "time_to_remaining_peak",
                "time_to_highmotion_threshold_crossing",
            ):
                subset = latency.loc[
                    latency["quantity"].eq(quantity)
                    & latency["lead_definition"].eq(definition)
                    & np.isclose(latency["assumed_total_latency_sec"], assumed_latency)
                ]
                if len(subset) == 1:
                    row = subset.iloc[0]
                    lines.append(
                        f"  {quantity.upper()} {definition}: positive net lead="
                        f"{100*row['fraction_positive_net_lead']:.1f}%, "
                        f">=2 s={100*row['fraction_net_lead_ge_2s']:.1f}%, "
                        f"median net={row['median_net_lead_sec']:.2f} s."
                    )
        lines.append("")

    lines.append("Use the values above to replace bracketed placeholders in the Section 2.5 draft.")
    out_path.write_text("\n".join(lines), encoding="utf-8")



def write_manuscript_draft(
    distribution: pd.DataFrame,
    latency: pd.DataFrame,
    effects: pd.DataFrame,
    audit: dict[str, object],
    out_path: Path,
) -> None:
    """Write a manuscript-ready Section 2.5 populated from the locked outputs."""

    def require_dist(quantity: str, definition: str) -> pd.Series:
        row = get_row(distribution, quantity, definition)
        if row is None:
            raise RuntimeError(f"Missing lead distribution row: {quantity}/{definition}")
        return row

    def require_effect(quantity: str, minimum: float, metric: str) -> pd.Series:
        row = effect_row(effects, quantity, minimum, metric)
        if row is None:
            raise RuntimeError(f"Missing minimum-lead effect row: {quantity}/{minimum}/{metric}")
        return row

    def require_latency(quantity: str, definition: str, latency_sec: float) -> pd.Series:
        row = latency.loc[
            latency["quantity"].eq(quantity)
            & latency["lead_definition"].eq(definition)
            & np.isclose(latency["assumed_total_latency_sec"], latency_sec)
        ]
        if len(row) != 1:
            raise RuntimeError(
                f"Missing latency row: {quantity}/{definition}/{latency_sec}"
            )
        return row.iloc[0]

    pga_peak = require_dist("pga", "time_to_remaining_peak")
    pgv_peak = require_dist("pgv", "time_to_remaining_peak")
    pga_cross = require_dist("pga", "time_to_highmotion_threshold_crossing")
    pgv_cross = require_dist("pgv", "time_to_highmotion_threshold_crossing")

    pga_pos = require_effect("pga", 0.0, "mae")
    pgv_pos = require_effect("pgv", 0.0, "mae")
    pga_5 = require_effect("pga", 5.0, "mae")
    pgv_5 = require_effect("pgv", 5.0, "mae")
    pga_10 = require_effect("pga", 10.0, "mae")
    pgv_10 = require_effect("pgv", 10.0, "mae")

    pga_latency_1 = require_latency("pga", "time_to_remaining_peak", 1.0)
    pgv_latency_1 = require_latency("pgv", "time_to_remaining_peak", 1.0)
    pga_cross_latency_1 = require_latency(
        "pga", "time_to_highmotion_threshold_crossing", 1.0
    )
    pgv_cross_latency_1 = require_latency(
        "pgv", "time_to_highmotion_threshold_crossing", 1.0
    )
    pga_latency_2 = require_latency("pga", "time_to_remaining_peak", 2.0)
    pgv_latency_2 = require_latency("pgv", "time_to_remaining_peak", 2.0)

    def effect_sentence(quantity: str, row: pd.Series, lead_label: str) -> str:
        ci_excludes_zero = float(row["delta_ci_upper"]) < 0.0
        qualifier = (
            "and the confidence interval excluded zero"
            if ci_excludes_zero
            else "although the confidence interval included zero"
        )
        return (
            f"For {quantity}, among targets with {lead_label}, tail MAE changed from "
            f"{row['cross_attention_value']:.3f} for the Cross-Attention Base to "
            f"{row['ca_urc_value']:.3f} for CA-URC (paired difference, "
            f"{row['delta_caurc_minus_base']:+.3f}; 95% confidence interval, "
            f"{row['delta_ci_lower']:+.3f} to {row['delta_ci_upper']:+.3f}; "
            f"n={int(row['n_events'])} earthquakes), {qualifier}."
        )

    positive_lead_supported = (
        float(pga_pos["delta_ci_upper"]) < 0.0
        and float(pgv_pos["delta_ci_upper"]) < 0.0
    )
    section_title = (
        "High-motion-tail improvements persist at positive warning lead times"
        if positive_lead_supported
        else "Physical warning lead times and latency sensitivity of high-motion forecasts"
    )
    concluding_claim = (
        "Its tail-error benefit remained statistically resolved in the positive-lead subsets for both PGA and PGV, supporting prospective warning relevance."
        if positive_lead_supported
        else "Point estimates in the positive-lead subsets remained favourable, but the uncertainty intervals did not resolve an improvement for both quantities; the result should therefore be interpreted as directional evidence rather than definitive prospective validation."
    )

    text = f"""{section_title}

The aggregate reductions in high-motion error reported above establish that CA-URC improves the locked test predictions, but they do not by themselves show whether those predictions precede the target motion of interest. We therefore linked each of the {audit['prediction_rows']:,} locked predictions from {audit['events']} earthquakes to the horizontal acceleration and velocity waveforms at the corresponding target station. Physical lead time was measured from the 5-s causal snapshot to either the remaining post-snapshot PGA or PGV peak or the first post-snapshot crossing of the training-derived high-motion threshold. Lead-time distributions were computed over unique event-station pairs so that repeatedly sampled targets did not receive additional weight, whereas prediction metrics retained the prespecified targets-to-repeats-to-events aggregation. No model retraining, checkpoint selection or threshold recalculation was performed for this analysis.

A substantial fraction of the high-motion target-station records retained positive physical lead after the causal snapshot (Fig. 6a). The median time to the remaining PGA peak was {pga_peak['median_sec']:.2f} s (interquartile range, {pga_peak['p25_sec']:.2f}-{pga_peak['p75_sec']:.2f} s), and {100*pga_peak['fraction_ge_2s']:.1f}%, {100*pga_peak['fraction_ge_5s']:.1f}% and {100*pga_peak['fraction_ge_10s']:.1f}% of the unique high-motion PGA targets retained at least 2, 5 and 10 s, respectively. For PGV, the median time to the remaining peak was {pgv_peak['median_sec']:.2f} s (interquartile range, {pgv_peak['p25_sec']:.2f}-{pgv_peak['p75_sec']:.2f} s), with corresponding fractions of {100*pgv_peak['fraction_ge_2s']:.1f}%, {100*pgv_peak['fraction_ge_5s']:.1f}% and {100*pgv_peak['fraction_ge_10s']:.1f}%. The first crossing of the high-motion threshold occurred earlier than the remaining peak, with median leads of {pga_cross['median_sec']:.2f} s for PGA and {pgv_cross['median_sec']:.2f} s for PGV. These distributions confirm that the task concerns motion that remained after the information cut-off rather than reconstruction of a peak already observed at the target.

{effect_sentence('PGA', pga_pos, 'a positive time to the remaining peak')} {effect_sentence('PGV', pgv_pos, 'a positive time to the remaining peak')} The benefit was also evaluated in progressively more prospective subsets. For targets retaining at least 5 s before the remaining peak, the paired tail-MAE differences were {pga_5['delta_caurc_minus_base']:+.3f} for PGA (95% confidence interval, {pga_5['delta_ci_lower']:+.3f} to {pga_5['delta_ci_upper']:+.3f}) and {pgv_5['delta_caurc_minus_base']:+.3f} for PGV ({pgv_5['delta_ci_lower']:+.3f} to {pgv_5['delta_ci_upper']:+.3f}; Supplementary Fig. X). For the at-least-10-s subsets, the corresponding differences were {pga_10['delta_caurc_minus_base']:+.3f} and {pgv_10['delta_caurc_minus_base']:+.3f}. Estimates across individual 0-1, 1-2, 2-5, 5-10, 10-20 and at-least-20-s bins are shown in Fig. 6c-f; uncertainty widened in bins supported by fewer earthquakes.

We next examined how assumed end-to-end processing latency would reduce the physically available lead (Fig. 6b). After subtracting 1 s, {100*pga_latency_1['fraction_positive_net_lead']:.1f}% of high-motion PGA targets and {100*pgv_latency_1['fraction_positive_net_lead']:.1f}% of high-motion PGV targets retained positive lead to the remaining peak. Positive lead to the first high-motion-threshold crossing remained for {100*pga_cross_latency_1['fraction_positive_net_lead']:.1f}% and {100*pgv_cross_latency_1['fraction_positive_net_lead']:.1f}% of the corresponding targets. Under a 2-s latency scenario, {100*pga_latency_2['fraction_positive_net_lead']:.1f}% of PGA targets and {100*pgv_latency_2['fraction_positive_net_lead']:.1f}% of PGV targets still preceded the remaining peak. These latency values are scenario-based subtractions rather than measured deployment latencies and therefore quantify physical opportunity rather than end-to-end operational performance.

Together, the timestamp audit shows that the aggregate CA-URC improvement is not restricted to target peaks occurring at the issue time. {concluding_claim} Nevertheless, short-lead targets and the reduction produced by assumed processing latency define an important operating boundary; a field deployment must additionally account for waveform telemetry, preprocessing, inference and alert-delivery delays.
"""
    out_path.write_text(text, encoding="utf-8")


def write_captions(audit: dict[str, object], out_dir: Path) -> None:
    main_caption = (
        "Fig. 6 | High-motion-tail improvements are evaluated against the physical time remaining before target motion. "
        "a, Empirical cumulative distributions of the time from the 5-s causal snapshot to the remaining PGA and PGV peaks "
        "for unique high-motion event-station pairs. Vertical dotted lines mark 2, 5 and 10 s. "
        "b, Fraction of high-motion targets retaining positive net lead to the remaining peak or to the first crossing of the "
        "training-derived high-motion threshold after subtracting assumed end-to-end system latency. "
        "c,d, High-motion-tail event-macro MAE as a function of time to the remaining PGA and PGV peaks. "
        "e,f, Severe-underprediction rate, U_0.5 = Pr(prediction - observation <= -0.5), across the same lead-time bins. "
        "Points and intervals in c-f denote estimates and 95% confidence intervals from paired hierarchical sequence-to-event "
        "bootstrap resampling; bins with fewer than the prespecified minimum number of events are omitted. Physical lead-time "
        "distributions are computed from unique event-station pairs to avoid weighting stations by repeated target selection. "
        f"The locked evaluation comprised {audit['events']} earthquakes, {audit['sequence_groups']} seismic-sequence groups and "
        f"{audit['prediction_rows']:,} prediction rows."
    )
    supplementary_caption = (
        "Supplementary Fig. X | CA-URC-minus-Base high-motion-tail MAE differences for targets with progressively larger minimum "
        "time to the remaining peak. Negative values favour CA-URC. Points and horizontal intervals denote paired event-macro "
        "differences and 95% confidence intervals obtained using hierarchical sequence-to-event bootstrap resampling. "
        "The >0-s subset contains only targets whose remaining peak occurred after the causal snapshot."
    )
    (out_dir / "Fig6_caption.txt").write_text(main_caption, encoding="utf-8")
    (out_dir / "FigS_caption.txt").write_text(supplementary_caption, encoding="utf-8")


def save_tables(
    distribution: pd.DataFrame,
    latency: pd.DataFrame,
    metrics: pd.DataFrame,
    effects: pd.DataFrame,
    out_dir: Path,
) -> None:
    tables = {
        "TableS5_physical_lead_distribution": distribution,
        "TableS5_latency_sensitivity": latency,
        "TableS5_metrics_by_peak_lead": metrics,
        "TableS5_minimum_lead_effects": effects,
    }
    for name, table in tables.items():
        table.to_csv(out_dir / f"{name}.csv", index=False)
        latex = dataframe_to_latex(table)
        (out_dir / f"{name}.tex").write_text(latex, encoding="utf-8")


def make_demo(seed: int = 20260713) -> tuple[pd.DataFrame, dict[str, object]]:
    """Create synthetic data ONLY for checking figure layout."""
    rng = np.random.default_rng(seed)
    n_events = 224
    repeats = 20
    targets = 10
    rows: list[dict[str, object]] = []
    event_groups = np.arange(n_events) % 22
    for event_index in range(n_events):
        event_id = f"demo_{event_index:04d}"
        sequence_group = f"seq_{event_groups[event_index]:02d}"
        station_truth_pga = rng.normal(-2.7, 0.55, size=30)
        station_truth_pgv = rng.normal(-4.0, 0.55, size=30)
        pga_threshold = np.quantile(station_truth_pga, 0.90)
        pgv_threshold = np.quantile(station_truth_pgv, 0.90)
        station_peak_pga = np.maximum(0.0, rng.gamma(1.7, 4.2, size=30) - 0.4)
        station_peak_pgv = np.maximum(0.0, rng.gamma(1.8, 4.7, size=30) - 0.4)
        station_cross_pga = np.maximum(0.0, station_peak_pga - rng.uniform(0.3, 2.4, size=30))
        station_cross_pgv = np.maximum(0.0, station_peak_pgv - rng.uniform(0.3, 2.8, size=30))
        for repeat in range(repeats):
            selected = rng.choice(30, size=targets, replace=False)
            for slot, station_index in enumerate(selected):
                true_pga = station_truth_pga[station_index]
                true_pgv = station_truth_pgv[station_index]
                tail_pga = bool(true_pga >= pga_threshold)
                tail_pgv = bool(true_pgv >= pgv_threshold)
                lead_pga = float(station_peak_pga[station_index])
                lead_pgv = float(station_peak_pgv[station_index])
                base_res_pga = rng.normal(-0.60 if tail_pga else -0.01, 0.26)
                base_res_pgv = rng.normal(-0.68 if tail_pgv else -0.03, 0.27)
                correction_pga = max(0.0, rng.normal(0.12 if tail_pga else 0.02, 0.05))
                correction_pgv = max(0.0, rng.normal(0.16 if tail_pgv else 0.02, 0.06))
                rows.append(
                    {
                        "event_id": event_id,
                        "repeat": repeat,
                        "target_station_index": int(station_index),
                        "true_log10_pga": true_pga,
                        "true_log10_pgv": true_pgv,
                        "is_tail_pga": tail_pga,
                        "is_tail_pgv": tail_pgv,
                        "cross_attention_log10_pga": true_pga + base_res_pga,
                        "cross_attention_log10_pgv": true_pgv + base_res_pgv,
                        "ca_urc_log10_pga": true_pga + base_res_pga + correction_pga,
                        "ca_urc_log10_pgv": true_pgv + base_res_pgv + correction_pgv,
                        "lead_to_pga_peak_sec": lead_pga,
                        "lead_to_pgv_peak_sec": lead_pgv,
                        "pga_highmotion_crossing_lead_sec": float(station_cross_pga[station_index]),
                        "pgv_highmotion_crossing_lead_sec": float(station_cross_pgv[station_index]),
                        "pga_peak_near_window_end": False,
                        "pgv_peak_near_window_end": False,
                        "sequence_group": sequence_group,
                    }
                )
    frame = pd.DataFrame(rows)
    audit = {
        "prediction_rows": int(len(frame)),
        "merged_rows": int(len(frame)),
        "events": int(frame["event_id"].nunique()),
        "sequence_groups": int(frame["sequence_group"].nunique()),
        "unique_event_station_pairs": int(
            frame[["event_id", "target_station_index"]].drop_duplicates().shape[0]
        ),
        "pga_tail_rows": int(frame["is_tail_pga"].sum()),
        "pgv_tail_rows": int(frame["is_tail_pgv"].sum()),
        "pga_tail_events": int(frame.loc[frame["is_tail_pga"], "event_id"].nunique()),
        "pgv_tail_events": int(frame.loc[frame["is_tail_pgv"], "event_id"].nunique()),
        "max_abs_truth_diff_pga": 0.0,
        "max_abs_truth_diff_pgv": 0.0,
        "demo": True,
    }
    return frame, audit


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--predictions",
        default=(
            "runs/cadrg_gate_ablation_A3_A5/"
            "locked_test_ablation_predictions.csv"
        ),
    )
    parser.add_argument(
        "--lead-times",
        default=(
            "runs/phase2_warning_lead_time/"
            "unique_event_station_lead_times.csv"
        ),
    )
    parser.add_argument(
        "--manifest",
        default="model_manifests/scenario_t0_5s_k5_linux.csv",
    )
    parser.add_argument("--split-column", default="split_grouped")
    parser.add_argument("--test-label", default="test")
    parser.add_argument("--sequence-column", default="sequence_group")
    parser.add_argument("--lead-bin-edges", default="0,1,2,5,10,20")
    parser.add_argument("--latencies", default="0,0.5,1,2")
    parser.add_argument("--minimum-leads", default="0,1,2,5,10")
    parser.add_argument("--minimum-events-per-bin", type=int, default=10)
    parser.add_argument("--bootstrap-repetitions", type=int, default=10000)
    parser.add_argument("--confidence-level", type=float, default=0.95)
    parser.add_argument("--seed", type=int, default=20260713)
    parser.add_argument("--dpi", type=int, default=600)
    parser.add_argument("--out-dir", default="figures/nc_section_2_5")
    parser.add_argument("--skip-locked-audit", action="store_true")
    parser.add_argument("--demo", action="store_true")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.demo:
        frame, audit = make_demo(args.seed)
    else:
        frame, audit = load_and_merge(
            Path(args.predictions),
            Path(args.lead_times),
            Path(args.manifest),
            args.split_column,
            args.test_label,
            args.sequence_column,
        )
        expected = {
            "prediction_rows": 44800,
            "events": 224,
            "sequence_groups": 22,
            "pga_tail_rows": 1363,
            "pgv_tail_rows": 1485,
            "pga_tail_events": 98,
            "pgv_tail_events": 87,
        }
        problems = [
            f"{key}: observed={audit[key]}, expected={value}"
            for key, value in expected.items()
            if int(audit[key]) != int(value)
        ]
        if problems:
            raise RuntimeError("Locked row-count audit failed:\n  " + "\n  ".join(problems))
        if not args.skip_locked_audit:
            locked_metric_audit(frame)

    unique_pairs = unique_physical_pairs(frame)
    edges = parse_float_list(args.lead_bin_edges)
    latencies = parse_float_list(args.latencies)
    minimum_leads = parse_float_list(args.minimum_leads)

    distribution = lead_distribution_table(unique_pairs)
    latency = latency_sensitivity_table(unique_pairs, latencies)
    metrics = metrics_by_peak_lead(
        frame,
        edges=edges,
        repetitions=args.bootstrap_repetitions,
        confidence=args.confidence_level,
        seed=args.seed,
        minimum_events=args.minimum_events_per_bin,
    )
    effects = minimum_lead_effects(
        frame,
        minimum_leads=minimum_leads,
        repetitions=args.bootstrap_repetitions,
        confidence=args.confidence_level,
        seed=args.seed,
    )

    plot_main_figure(unique_pairs, latency, metrics, out_dir, args.dpi)
    plot_minimum_lead_figure(effects, out_dir, args.dpi)
    save_tables(distribution, latency, metrics, effects, out_dir)
    write_manuscript_numbers(
        distribution,
        latency,
        effects,
        audit,
        out_dir / "Section2_5_manuscript_numbers.txt",
    )
    write_manuscript_draft(
        distribution,
        latency,
        effects,
        audit,
        out_dir / "Section2_5_manuscript_draft.txt",
    )
    write_captions(audit, out_dir)

    edge_audit = pd.DataFrame(
        [
            {
                "quantity": "pga",
                "n_unique_event_station_pairs": int(len(unique_pairs)),
                "n_peak_near_window_end": int(unique_pairs["pga_peak_near_window_end"].sum()),
                "fraction_peak_near_window_end": float(unique_pairs["pga_peak_near_window_end"].mean()),
            },
            {
                "quantity": "pgv",
                "n_unique_event_station_pairs": int(len(unique_pairs)),
                "n_peak_near_window_end": int(unique_pairs["pgv_peak_near_window_end"].sum()),
                "fraction_peak_near_window_end": float(unique_pairs["pgv_peak_near_window_end"].mean()),
            },
        ]
    )
    edge_audit.to_csv(out_dir / "TableS5_future_window_edge_audit.csv", index=False)

    configuration = {
        **vars(args),
        "audit": audit,
        "lead_time_origin": "t0=5-s causal snapshot",
        "physical_distribution_weighting": "unique event-station pairs",
        "metric_hierarchy": "targets -> repeats -> events -> sequence-aware bootstrap",
        "delta_definition": "CA-URC - Cross-Attention Base",
        "high_motion_labels_recomputed": False,
        "model_training_performed": False,
        "model_selection_performed": False,
    }
    (out_dir / "run_configuration.json").write_text(
        json.dumps(configuration, indent=2), encoding="utf-8"
    )

    print("=== NC Section 2.5 warning lead-time analysis ===")
    print(json.dumps(audit, indent=2))
    print("\nHigh-motion physical lead distributions:")
    print(distribution.to_string(index=False))
    print("\nMinimum-lead paired effects:")
    print(effects.loc[effects["metric"].eq("mae")].to_string(index=False))
    print("\nOutputs:")
    for path in sorted(out_dir.iterdir()):
        print(" ", path.resolve())


if __name__ == "__main__":
    main()
