#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Supplementary Fig. S8 and Supplementary Table 8 for the CA-URC manuscript.

Purpose
-------
Summarise robustness that does not require any further model selection:
  a) validation-only epoch x gamma selection landscape;
  b) high-motion-tail MAE benefit across warning-lead strata;
  c) geometry-matching caliper sensitivity at unseen stations;
  d) sensitivity to the sequence-aware bootstrap scheme.

The locked final model remains:
    CA-URC = A4_under_only, epoch=3, gamma=5.
This script never changes the selected model and never trains a model.

Expected inputs
---------------
1. Gamma scan:
   runs/cadrg_gate_ablation_A3_A5/A4_under_only/
       epoch_gamma_validation_scan.csv
2. Lead-bin results generated by Fig6_NC_warning_lead_time.py:
   figures/nc_section_2_5/TableS5_metrics_by_peak_lead.csv
3. Station matching balance:
   runs/caurc_station_ood_matched_geometry/matching_balance_summary.csv
4. Station matching bootstrap:
   runs/caurc_station_ood_matched_geometry/matched_geometry_event_bootstrap.csv
5. Sequence-aware bootstrap summary:
   runs/caurc_sequence_aware_bootstrap/all_sequence_aware_bootstrap_summary.csv

Outputs
-------
FigS8_robustness_sensitivity.{png,pdf,svg}
FigS8_caption.txt
Section2_8_manuscript_draft.txt
TableS8_validation_selection.csv
TableS8_lead_time_sensitivity.csv
TableS8_station_caliper_sensitivity.csv
TableS8_bootstrap_scheme_sensitivity.csv
remaining_required_experiments.txt
run_configuration.json

Use --demo only to inspect layout. Demo values are synthetic and are visibly labelled.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


LOCKED_EPOCH = 3
LOCKED_GAMMA = 5.0
LEAD_ORDER = ["0-1", "1-2", "2-5", "5-10", "10-20", ">=20"]
QUANTITY_LABEL = {"pga": "PGA", "pgv": "PGV"}


# -----------------------------------------------------------------------------
# General utilities
# -----------------------------------------------------------------------------

def parse_bool(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    text = series.astype(str).str.strip().str.lower()
    true_values = {"true", "1", "yes", "y", "t"}
    false_values = {"false", "0", "no", "n", "f", "nan", "none", ""}
    unknown = set(text.unique()).difference(true_values | false_values)
    if unknown:
        raise ValueError(f"Cannot parse boolean values: {sorted(unknown)[:20]}")
    return text.isin(true_values)


def require_columns(frame: pd.DataFrame, columns: Iterable[str], name: str) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}")


def finite_float(value: object, default: float = np.nan) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return default
    return out if np.isfinite(out) else default


def canonical_lead_bin(value: object) -> str:
    text = str(value).strip()
    replacements = {
        "–": "-",
        "—": "-",
        "−": "-",
        "s": "",
        " ": "",
        "≥": ">=",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    if text.startswith(">20"):
        text = ">=20"
    if text in {"20+", "20-inf", "20-infinity", "20-∞"}:
        text = ">=20"
    if text not in LEAD_ORDER:
        raise ValueError(
            f"Unsupported lead bin {value!r}; expected one of {LEAD_ORDER}."
        )
    return text


def style_axis(axis: plt.Axes, grid: str = "y") -> None:
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.set_axisbelow(True)
    if grid == "x":
        axis.grid(axis="x", linewidth=0.55, alpha=0.22)
    elif grid == "y":
        axis.grid(axis="y", linewidth=0.55, alpha=0.22)
    elif grid == "both":
        axis.grid(linewidth=0.5, alpha=0.18)


def panel_label(axis: plt.Axes, label: str) -> None:
    axis.text(
        -0.16,
        1.06,
        label,
        transform=axis.transAxes,
        ha="left",
        va="bottom",
        fontsize=10.5,
        fontweight="bold",
    )


def setup_matplotlib() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 8.2,
            "axes.labelsize": 8.8,
            "axes.titlesize": 9.0,
            "xtick.labelsize": 7.6,
            "ytick.labelsize": 7.6,
            "legend.fontsize": 7.3,
            "axes.linewidth": 0.8,
            "xtick.major.width": 0.8,
            "ytick.major.width": 0.8,
            "xtick.major.size": 3.0,
            "ytick.major.size": 3.0,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
        }
    )


# -----------------------------------------------------------------------------
# Input normalisation
# -----------------------------------------------------------------------------

def prepare_gamma_scan(path: Path) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    frame = pd.read_csv(path)
    require_columns(frame, ["epoch", "gamma"], "gamma scan")

    if "mean_tail_mae" not in frame.columns:
        require_columns(frame, ["tail_mae_pga", "tail_mae_pgv"], "gamma scan")
        frame["mean_tail_mae"] = 0.5 * (
            pd.to_numeric(frame["tail_mae_pga"], errors="coerce")
            + pd.to_numeric(frame["tail_mae_pgv"], errors="coerce")
        )
    if "mean_tail_under05" not in frame.columns:
        if {"tail_under05_pga", "tail_under05_pgv"}.issubset(frame.columns):
            frame["mean_tail_under05"] = 0.5 * (
                pd.to_numeric(frame["tail_under05_pga"], errors="coerce")
                + pd.to_numeric(frame["tail_under05_pgv"], errors="coerce")
            )
        else:
            frame["mean_tail_under05"] = np.nan
    if "mean_overall_mae" not in frame.columns:
        require_columns(frame, ["overall_mae_pga", "overall_mae_pgv"], "gamma scan")
        frame["mean_overall_mae"] = 0.5 * (
            pd.to_numeric(frame["overall_mae_pga"], errors="coerce")
            + pd.to_numeric(frame["overall_mae_pgv"], errors="coerce")
        )
    if "feasible" not in frame.columns:
        raise ValueError(
            "Gamma scan must contain a validation-only 'feasible' column. "
            "Do not reconstruct feasibility from test performance."
        )

    frame["epoch"] = pd.to_numeric(frame["epoch"], errors="raise").astype(int)
    frame["gamma"] = pd.to_numeric(frame["gamma"], errors="raise").astype(float)
    frame["feasible"] = parse_bool(frame["feasible"])

    metric_columns = ["mean_tail_mae", "mean_tail_under05", "mean_overall_mae"]
    for column in metric_columns:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")

    feasible = frame.loc[frame["feasible"]].copy()
    if feasible.empty:
        raise RuntimeError("No feasible validation candidates were found.")

    selected = feasible.sort_values(
        ["mean_tail_mae", "mean_tail_under05", "mean_overall_mae", "gamma", "epoch"],
        ascending=True,
        na_position="last",
    ).iloc[0]

    if int(selected["epoch"]) != LOCKED_EPOCH or not np.isclose(
        float(selected["gamma"]), LOCKED_GAMMA
    ):
        raise RuntimeError(
            "Validation scan does not reproduce the locked final selection: "
            f"observed epoch={int(selected['epoch'])}, gamma={float(selected['gamma']):g}; "
            f"expected epoch={LOCKED_EPOCH}, gamma={LOCKED_GAMMA:g}."
        )

    gamma_summary = (
        feasible.groupby("gamma", as_index=False)
        .agg(
            feasible_candidates=("epoch", "size"),
            minimum_mean_tail_mae=("mean_tail_mae", "min"),
            median_mean_tail_mae=("mean_tail_mae", "median"),
            p10_mean_tail_mae=("mean_tail_mae", lambda s: float(np.nanpercentile(s, 10))),
            p90_mean_tail_mae=("mean_tail_mae", lambda s: float(np.nanpercentile(s, 90))),
        )
        .sort_values("gamma")
    )
    return frame, selected, gamma_summary


def prepare_lead_sensitivity(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    require_columns(
        frame,
        [
            "quantity",
            "lead_bin",
            "metric",
            "cross_attention_value",
            "ca_urc_value",
            "delta_caurc_minus_base",
            "delta_ci_lower",
            "delta_ci_upper",
            "n_events",
        ],
        "lead-bin table",
    )
    frame["quantity"] = frame["quantity"].astype(str).str.lower()
    frame["metric"] = frame["metric"].astype(str).str.lower()
    frame = frame.loc[
        frame["quantity"].isin(["pga", "pgv"]) & frame["metric"].eq("mae")
    ].copy()
    if "display_eligible" in frame.columns:
        frame = frame.loc[parse_bool(frame["display_eligible"])].copy()
    frame["lead_bin"] = frame["lead_bin"].map(canonical_lead_bin)

    for column in [
        "cross_attention_value",
        "ca_urc_value",
        "delta_caurc_minus_base",
        "delta_ci_lower",
        "delta_ci_upper",
    ]:
        frame[column] = pd.to_numeric(frame[column], errors="raise")
    frame["n_events"] = pd.to_numeric(frame["n_events"], errors="raise").astype(int)

    if frame.duplicated(["quantity", "lead_bin"]).any():
        raise ValueError("Lead-bin table contains duplicate quantity/bin rows.")

    # Positive values denote a reduction in tail MAE.
    frame["reduction_percent"] = (
        -100.0
        * frame["delta_caurc_minus_base"]
        / frame["cross_attention_value"].abs().clip(lower=1e-12)
    )
    frame["reduction_ci_lower"] = (
        -100.0
        * frame["delta_ci_upper"]
        / frame["cross_attention_value"].abs().clip(lower=1e-12)
    )
    frame["reduction_ci_upper"] = (
        -100.0
        * frame["delta_ci_lower"]
        / frame["cross_attention_value"].abs().clip(lower=1e-12)
    )
    frame["lead_order"] = frame["lead_bin"].map({v: i for i, v in enumerate(LEAD_ORDER)})
    return frame.sort_values(["quantity", "lead_order"])


def prepare_caliper_sensitivity(
    balance_path: Path, bootstrap_path: Path
) -> tuple[pd.DataFrame, pd.DataFrame]:
    balance = pd.read_csv(balance_path)
    bootstrap = pd.read_csv(bootstrap_path)
    require_columns(
        balance,
        [
            "caliper_km",
            "matched_events",
            "matched_pairs",
            "median_abs_distance_difference_km",
        ],
        "matching-balance table",
    )
    require_columns(
        bootstrap,
        [
            "caliper_km",
            "comparison_type",
            "group_or_model",
            "quantity",
            "population",
            "metric",
            "n_events",
            "point_delta",
            "ci_lower",
            "ci_upper",
        ],
        "matching bootstrap table",
    )

    for frame in (balance, bootstrap):
        frame["caliper_km"] = pd.to_numeric(frame["caliper_km"], errors="raise")

    effect = bootstrap.loc[
        bootstrap["comparison_type"].astype(str).str.lower().eq("caurc_minus_base")
        & bootstrap["group_or_model"].astype(str).str.lower().eq("unseen_station_target")
        & bootstrap["population"].astype(str).str.lower().eq("high_motion_tail")
        & bootstrap["metric"].astype(str).str.lower().eq("mae")
        & bootstrap["quantity"].astype(str).str.lower().isin(["pga", "pgv"])
    ].copy()
    effect["quantity"] = effect["quantity"].astype(str).str.lower()
    if effect.empty:
        raise ValueError(
            "No unseen-station high-motion-tail MAE rows were found in the matching bootstrap table."
        )
    if effect.duplicated(["caliper_km", "quantity"]).any():
        raise ValueError("Matching bootstrap contains duplicate caliper/quantity rows.")

    effect = effect.merge(
        balance[
            [
                "caliper_km",
                "matched_events",
                "matched_pairs",
                "median_abs_distance_difference_km",
            ]
        ],
        on="caliper_km",
        how="left",
        validate="many_to_one",
    )
    effect["improvement"] = -pd.to_numeric(effect["point_delta"], errors="raise")
    effect["improvement_ci_lower"] = -pd.to_numeric(effect["ci_upper"], errors="raise")
    effect["improvement_ci_upper"] = -pd.to_numeric(effect["ci_lower"], errors="raise")
    return balance.sort_values("caliper_km"), effect.sort_values(["quantity", "caliper_km"])


def prepare_bootstrap_sensitivity(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    require_columns(
        frame,
        [
            "candidate",
            "reference",
            "quantity",
            "population",
            "metric",
            "bootstrap_mode",
            "point_delta_candidate_minus_reference",
            "ci_lower",
            "ci_upper",
        ],
        "sequence-aware bootstrap table",
    )
    candidate = frame["candidate"].astype(str).str.lower().str.replace("-", "_", regex=False)
    reference = frame["reference"].astype(str).str.lower().str.replace("-", "_", regex=False)
    mode = frame["bootstrap_mode"].astype(str).str.lower()
    out = frame.loc[
        candidate.isin({"ca_urc", "caurc", "a4_under_only"})
        & reference.isin({"cross_attention", "cross_attention_base", "s3"})
        & frame["quantity"].astype(str).str.lower().isin(["pga", "pgv"])
        & frame["population"].astype(str).str.lower().eq("high_motion_tail")
        & frame["metric"].astype(str).str.lower().eq("mae")
        & mode.isin({"hierarchical_sequence_event", "sequence_cluster"})
    ].copy()
    out["quantity"] = out["quantity"].astype(str).str.lower()
    out["bootstrap_mode"] = mode.loc[out.index]
    if out.duplicated(["quantity", "bootstrap_mode"]).any():
        raise ValueError("Duplicate quantity/bootstrap-mode rows were found.")
    expected = {(q, m) for q in ("pga", "pgv") for m in ("hierarchical_sequence_event", "sequence_cluster")}
    observed = set(zip(out["quantity"], out["bootstrap_mode"]))
    if observed != expected:
        raise ValueError(
            "Bootstrap table must contain both hierarchical_sequence_event and "
            f"sequence_cluster rows for PGA and PGV. Missing: {sorted(expected-observed)}"
        )
    for column in ["point_delta_candidate_minus_reference", "ci_lower", "ci_upper"]:
        out[column] = pd.to_numeric(out[column], errors="raise")
    return out.sort_values(["quantity", "bootstrap_mode"])


# -----------------------------------------------------------------------------
# Demo data
# -----------------------------------------------------------------------------

def demo_inputs(seed: int = 20260713):
    rng = np.random.default_rng(seed)
    gammas = np.array([1, 1.5, 2, 2.5, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20], float)
    rows = []
    for epoch in range(1, 41):
        for gamma in gammas:
            score = 0.61 + 0.00018 * (epoch - 3) ** 2 + 0.0018 * (np.log1p(gamma) - np.log1p(5)) ** 2
            score += rng.normal(0, 0.006)
            feasible = rng.random() < 0.64
            rows.append(
                {
                    "epoch": epoch,
                    "gamma": gamma,
                    "mean_tail_mae": score,
                    "mean_tail_under05": 0.52 + rng.normal(0, 0.015),
                    "mean_overall_mae": 0.30 + rng.normal(0, 0.002),
                    "feasible": feasible,
                }
            )
    gamma = pd.DataFrame(rows)
    gamma.loc[:, "feasible"] = False
    chosen = rng.choice(gamma.index, size=355, replace=False)
    gamma.loc[chosen, "feasible"] = True
    locked_index = gamma.index[(gamma.epoch == 3) & np.isclose(gamma.gamma, 5.0)][0]
    gamma.loc[locked_index, ["feasible", "mean_tail_mae", "mean_tail_under05", "mean_overall_mae"]] = [
        True,
        0.598,
        0.520,
        0.300,
    ]
    # Ensure the locked point is selected in demo.
    gamma.loc[gamma.index != locked_index, "mean_tail_mae"] = np.maximum(
        gamma.loc[gamma.index != locked_index, "mean_tail_mae"], 0.600
    )

    lead_rows = []
    for q, center in (("pga", 12.0), ("pgv", 15.5)):
        for i, b in enumerate(LEAD_ORDER):
            reduction = center + rng.normal(0, 2.0)
            base = 0.60 + 0.05 * i
            delta = -base * reduction / 100.0
            lead_rows.append(
                {
                    "quantity": q,
                    "lead_bin": b,
                    "metric": "mae",
                    "cross_attention_value": base,
                    "ca_urc_value": base + delta,
                    "delta_caurc_minus_base": delta,
                    "delta_ci_lower": delta - 0.012,
                    "delta_ci_upper": delta + 0.012,
                    "n_events": int(55 - 5 * i),
                    "display_eligible": True,
                }
            )
    lead = pd.DataFrame(lead_rows)

    balance = pd.DataFrame(
        {
            "caliper_km": [10.0, 20.0, 30.0],
            "matched_events": [195, 195, 195],
            "matched_pairs": [3248, 5649, 7148],
            "median_abs_distance_difference_km": [5.121, 8.897, 11.986],
        }
    )
    boot_rows = []
    for c in [10.0, 20.0, 30.0]:
        for q, d in (("pga", -0.060), ("pgv", -0.058)):
            jitter = rng.normal(0, 0.004)
            point = d + jitter
            boot_rows.append(
                {
                    "caliper_km": c,
                    "comparison_type": "caurc_minus_base",
                    "group_or_model": "unseen_station_target",
                    "quantity": q,
                    "population": "high_motion_tail",
                    "metric": "mae",
                    "n_events": 35 if q == "pga" else 30,
                    "point_delta": point,
                    "ci_lower": point - 0.018,
                    "ci_upper": point + 0.018,
                }
            )
    station_boot = pd.DataFrame(boot_rows)

    scheme_rows = []
    for q, d in (("pga", -0.072), ("pgv", -0.099)):
        for mode_name, width in (("hierarchical_sequence_event", 0.012), ("sequence_cluster", 0.030)):
            scheme_rows.append(
                {
                    "candidate": "ca_urc",
                    "reference": "cross_attention",
                    "quantity": q,
                    "population": "high_motion_tail",
                    "metric": "mae",
                    "bootstrap_mode": mode_name,
                    "point_delta_candidate_minus_reference": d,
                    "ci_lower": d - width,
                    "ci_upper": d + width,
                }
            )
    schemes = pd.DataFrame(scheme_rows)
    return gamma, lead, balance, station_boot, schemes


# -----------------------------------------------------------------------------
# Plotting
# -----------------------------------------------------------------------------

def make_figure(
    gamma_scan: pd.DataFrame,
    selected: pd.Series,
    lead: pd.DataFrame,
    balance: pd.DataFrame,
    caliper: pd.DataFrame,
    bootstrap: pd.DataFrame,
    out_dir: Path,
    dpi: int,
    demo: bool,
) -> None:
    setup_matplotlib()
    cycle = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    q_color = {"pga": cycle[0], "pgv": cycle[1]}

    fig, axes = plt.subplots(2, 2, figsize=(7.32, 5.55))
    ax_a, ax_b, ax_c, ax_d = axes.ravel()

    # a: validation-only selection landscape.
    feasible = gamma_scan.loc[gamma_scan["feasible"]].copy()
    infeasible = gamma_scan.loc[~gamma_scan["feasible"]].copy()
    ax_a.scatter(
        infeasible["gamma"],
        infeasible["mean_tail_mae"],
        s=8,
        alpha=0.10,
        linewidths=0,
        label="Constraint-violating",
    )
    ax_a.scatter(
        feasible["gamma"],
        feasible["mean_tail_mae"],
        s=9,
        alpha=0.32,
        linewidths=0,
        label="Feasible",
    )
    by_gamma = feasible.groupby("gamma", as_index=False)["mean_tail_mae"].min().sort_values("gamma")
    ax_a.plot(by_gamma["gamma"], by_gamma["mean_tail_mae"], linewidth=1.2, marker="o", markersize=2.8)
    ax_a.scatter(
        [float(selected["gamma"])],
        [float(selected["mean_tail_mae"])],
        marker="*",
        s=100,
        edgecolor="black",
        linewidth=0.6,
        zorder=8,
        label="Locked selection",
    )
    ax_a.set_xscale("log")
    gamma_ticks = sorted(gamma_scan["gamma"].unique())
    ax_a.set_xticks(gamma_ticks)
    ax_a.set_xticklabels([f"{g:g}" for g in gamma_ticks], rotation=45, ha="right")
    ax_a.set_xlabel(r"Gate exponent, $\gamma$")
    ax_a.set_ylabel("Mean validation tail MAE")
    ax_a.set_title("Validation-only gate selection")
    ax_a.text(
        0.98,
        0.98,
        f"{len(feasible)}/{len(gamma_scan)} feasible\nselected: epoch {int(selected['epoch'])}, $\\gamma$={float(selected['gamma']):g}",
        transform=ax_a.transAxes,
        ha="right",
        va="top",
        fontsize=7.2,
        bbox={"boxstyle": "round,pad=0.24", "facecolor": "white", "alpha": 0.86, "linewidth": 0.45},
    )
    style_axis(ax_a, "both")
    panel_label(ax_a, "a")

    # b: warning-lead strata.
    x = np.arange(len(LEAD_ORDER), dtype=float)
    offsets = {"pga": -0.12, "pgv": 0.12}
    for q in ("pga", "pgv"):
        sub = lead.loc[lead["quantity"].eq(q)].set_index("lead_bin").reindex(LEAD_ORDER)
        if sub["reduction_percent"].isna().any():
            raise ValueError(f"Lead table is incomplete for {q}.")
        y = sub["reduction_percent"].to_numpy(float)
        lo = y - sub["reduction_ci_lower"].to_numpy(float)
        hi = sub["reduction_ci_upper"].to_numpy(float) - y
        ax_b.errorbar(
            x + offsets[q],
            y,
            yerr=np.vstack([lo, hi]),
            marker="o" if q == "pga" else "s",
            markersize=4.0,
            linewidth=1.1,
            capsize=2.2,
            color=q_color[q],
            label=QUANTITY_LABEL[q],
        )
    ax_b.axhline(0.0, linewidth=0.8, color="0.25")
    ax_b.set_xticks(x)
    ax_b.set_xticklabels(["0-1", "1-2", "2-5", "5-10", "10-20", r"$\geq$20"])
    ax_b.set_xlabel("Time to remaining peak (s)")
    ax_b.set_ylabel("Tail-MAE reduction (%)")
    ax_b.set_title("Benefit across warning-lead strata")
    ax_b.legend(frameon=False, loc="upper right")
    style_axis(ax_b, "y")
    panel_label(ax_b, "b")

    # c: station matching calipers.
    for q in ("pga", "pgv"):
        sub = caliper.loc[caliper["quantity"].eq(q)].sort_values("caliper_km")
        y = sub["improvement"].to_numpy(float)
        lo = y - sub["improvement_ci_lower"].to_numpy(float)
        hi = sub["improvement_ci_upper"].to_numpy(float) - y
        ax_c.errorbar(
            sub["caliper_km"],
            y,
            yerr=np.vstack([lo, hi]),
            marker="o" if q == "pga" else "s",
            markersize=4.2,
            linewidth=1.2,
            capsize=2.3,
            color=q_color[q],
            label=QUANTITY_LABEL[q],
        )
    ax_c.axhline(0.0, linewidth=0.8, color="0.25")
    ax_c.set_xticks(sorted(balance["caliper_km"].unique()))
    ax_c.set_xlabel("Matching caliper (km)")
    ax_c.set_ylabel(r"Tail-MAE improvement ($\log_{10}$ units)")
    ax_c.set_title("Unseen-station matching sensitivity")
    # Put retained-pair counts above the larger of the two confidence intervals
    # at each caliper, rather than against the title.
    for row in balance.sort_values("caliper_km").itertuples(index=False):
        x_value = float(row.caliper_km)
        at_x = caliper.loc[np.isclose(caliper["caliper_km"], x_value)]
        y_anchor = float(at_x["improvement_ci_upper"].max())
        ax_c.annotate(
            f"n={int(row.matched_pairs):,}",
            xy=(x_value, y_anchor),
            xytext=(0, 4),
            textcoords="offset points",
            ha="center",
            va="bottom",
            fontsize=6.7,
            clip_on=False,
        )
    ymin, ymax = ax_c.get_ylim()
    ax_c.set_ylim(ymin, ymax + 0.08 * (ymax - ymin))
    ax_c.legend(frameon=False, loc="lower right")
    style_axis(ax_c, "y")
    panel_label(ax_c, "c")

    # d: bootstrap scheme sensitivity.
    scheme_label = {
        "hierarchical_sequence_event": "Hierarchical sequence-event",
        "sequence_cluster": "Sequence-cluster",
    }
    rows = []
    for q in ("pga", "pgv"):
        for mode in ("hierarchical_sequence_event", "sequence_cluster"):
            row = bootstrap.loc[
                bootstrap["quantity"].eq(q) & bootstrap["bootstrap_mode"].eq(mode)
            ].iloc[0]
            rows.append((q, mode, row))
    y_positions = np.arange(len(rows))[::-1]
    for ypos, (q, mode, row) in zip(y_positions, rows):
        point = float(row["point_delta_candidate_minus_reference"])
        low = float(row["ci_lower"])
        high = float(row["ci_upper"])
        marker = "o" if mode == "hierarchical_sequence_event" else "D"
        ax_d.errorbar(
            point,
            ypos,
            xerr=np.array([[point - low], [high - point]]),
            marker=marker,
            markersize=4.6,
            linewidth=1.1,
            capsize=2.2,
            color=q_color[q],
        )
    ax_d.axvline(0.0, linewidth=0.8, color="0.25")
    ax_d.set_yticks(y_positions)
    # Keep the row labels compact so this panel remains legible at two-column width.
    ax_d.set_yticklabels(
        [
            f"{QUANTITY_LABEL[q]} · "
            + ("H" if m == "hierarchical_sequence_event" else "C")
            for q, m, _ in rows
        ]
    )
    ax_d.set_xlabel(r"CA-URC - Base tail MAE ($\log_{10}$ units)")
    ax_d.set_title("Inference under two resampling schemes")
    style_axis(ax_d, "x")
    panel_label(ax_d, "d")

    marker_legend = [
        Line2D([0], [0], marker="o", linestyle="none", color="0.25", label="H: hierarchical sequence–event"),
        Line2D([0], [0], marker="D", linestyle="none", color="0.25", label="C: sequence-cluster"),
    ]
    ax_d.legend(handles=marker_legend, frameon=False, loc="lower left", fontsize=6.8)

    if demo:
        fig.text(
            0.5,
            0.995,
            "LAYOUT PREVIEW - SYNTHETIC VALUES - NOT FOR MANUSCRIPT USE",
            ha="center",
            va="top",
            fontsize=9.0,
            fontweight="bold",
        )

    fig.subplots_adjust(left=0.095, right=0.985, bottom=0.105, top=0.93, wspace=0.39, hspace=0.42)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = out_dir / "FigS8_robustness_sensitivity"
    fig.savefig(stem.with_suffix(".png"), dpi=dpi, bbox_inches="tight")
    fig.savefig(stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(stem.with_suffix(".svg"), bbox_inches="tight")
    plt.close(fig)


# -----------------------------------------------------------------------------
# Text and tables
# -----------------------------------------------------------------------------

def ci_excludes_zero(low: float, high: float) -> bool:
    return bool(low > 0.0 or high < 0.0)


def write_caption(
    gamma_scan: pd.DataFrame,
    selected: pd.Series,
    lead: pd.DataFrame,
    balance: pd.DataFrame,
    out_path: Path,
) -> None:
    caption = (
        "Supplementary Fig. S8 | Robustness of the CA-URC tail-risk result to "
        "validation selection and prespecified analysis choices. a, Validation-only "
        "epoch-by-gate-exponent landscape for the underprediction-risk correction head. "
        "Points denote candidate epoch-gamma combinations, the line traces the minimum "
        "mean tail MAE among feasible candidates at each gamma, and the star denotes the "
        f"locked selection (epoch {int(selected['epoch'])}, gamma={float(selected['gamma']):g}). "
        f"Overall, {int(gamma_scan['feasible'].sum())} of {len(gamma_scan)} candidates "
        "satisfied the prespecified catalogue-wide, non-tail and bias constraints. "
        "b, Relative reduction in high-motion-tail MAE across non-overlapping time-to-remaining-peak "
        "bins. Positive values favour CA-URC; intervals are 95% hierarchical sequence-to-event "
        "bootstrap confidence intervals. c, CA-URC tail-MAE improvement at geometry-matched unseen "
        "stations under 10-, 20- and 30-km nearest-input-distance calipers. Labels denote retained "
        "matched target pairs; matching used exact P-wave state and nearest-input distance only. "
        "d, CA-URC-minus-Base tail-MAE effects under hierarchical sequence-to-event and sequence-cluster "
        "bootstrap. Negative values favour CA-URC. Panels a, b and d refer to the locked grouped benchmark; "
        "panel c refers to the separately trained, leakage-safe station-OOD protocol. Within each panel, the "
        "model and target predictions were held fixed while only the stated analysis choice was varied, and no "
        "sensitivity result was used to alter a checkpoint or gate exponent."
    )
    out_path.write_text(caption, encoding="utf-8")


def write_manuscript(
    gamma_scan: pd.DataFrame,
    selected: pd.Series,
    lead: pd.DataFrame,
    balance: pd.DataFrame,
    caliper: pd.DataFrame,
    bootstrap: pd.DataFrame,
    out_path: Path,
) -> None:
    feasible_n = int(gamma_scan["feasible"].sum())
    total_n = int(len(gamma_scan))
    gamma_max = float(gamma_scan["gamma"].max())

    pga_lead = lead.loc[lead["quantity"].eq("pga")]
    pgv_lead = lead.loc[lead["quantity"].eq("pgv")]
    pga_min, pga_max = pga_lead["reduction_percent"].min(), pga_lead["reduction_percent"].max()
    pgv_min, pgv_max = pgv_lead["reduction_percent"].min(), pgv_lead["reduction_percent"].max()
    lead_all_mae_supported = bool(
        (lead["delta_ci_upper"] < 0.0).all()
    )

    def longest(q: str) -> pd.Series:
        return lead.loc[lead["quantity"].eq(q) & lead["lead_bin"].eq(">=20")].iloc[0]

    pga_long = longest("pga")
    pgv_long = longest("pgv")

    caliper_support = []
    for q in ("pga", "pgv"):
        sub = caliper.loc[caliper["quantity"].eq(q)]
        caliper_support.append(bool((sub["ci_upper"] < 0.0).all()))
    all_calipers_supported = all(caliper_support)

    bootstrap_support = []
    for q in ("pga", "pgv"):
        sub = bootstrap.loc[bootstrap["quantity"].eq(q)]
        bootstrap_support.append(bool((sub["ci_upper"] < 0.0).all()))
    both_bootstrap_supported = all(bootstrap_support)

    caliper_values = sorted(balance["caliper_km"].unique())
    pair_counts = {
        float(row.caliper_km): int(row.matched_pairs)
        for row in balance.itertuples(index=False)
    }

    if all_calipers_supported:
        caliper_sentence = (
            "The unseen-station tail-MAE effect retained a confidence interval below zero "
            f"under all three matching calipers ({', '.join(f'{v:g}' for v in caliper_values)} km), "
            "indicating that the conclusion was not determined by the primary 20-km choice."
        )
    else:
        caliper_sentence = (
            "Point estimates at the unseen stations remained favourable across the matching-caliper "
            "analysis, but at least one caliper-specific confidence interval included zero; the "
            "station result should therefore be interpreted as strongest under the prespecified "
            "20-km primary analysis rather than invariant to every matching choice."
        )

    if both_bootstrap_supported:
        bootstrap_sentence = (
            "For both PGA and PGV, the high-motion-tail MAE interval remained below zero under both "
            "the hierarchical sequence-to-event and the more conservative sequence-cluster bootstrap."
        )
    else:
        bootstrap_sentence = (
            "The point estimate remained favourable under both sequence-aware resampling schemes, "
            "but at least one sequence-cluster interval included zero; inferential strength therefore "
            "depends partly on how between-sequence variation is represented."
        )

    timing_sentence = (
        "All six warning-lead bins supported lower tail MAE for both quantities."
        if lead_all_mae_supported
        else "Tail-MAE point estimates were favourable across warning-lead bins, although at least one interval included zero."
    )

    text = f"""## Primary conclusions are not confined to a single gate setting or warning-time regime

We finally examined whether the primary tail-risk result depended on an isolated validation setting or a narrow subset of the physical warning-time distribution. The underprediction-risk correction head was evaluated over {total_n} validation-only epoch–gate-exponent combinations while the Cross-Attention Base remained frozen. Candidate configurations were required to satisfy the prespecified catalogue-wide MAE, non-tail MAE and bias safeguards for both PGA and PGV. Of these combinations, {feasible_n} were feasible. The final configuration was selected at epoch {int(selected['epoch'])} with $\\gamma={float(selected['gamma']):g}$ and did not occur at the upper boundary of the scanned range ($\\gamma={gamma_max:g}$; Supplementary Fig. S8a). The selected point was therefore not the only configuration satisfying the preservation constraints, although the validation scan should not be interpreted as independent test evidence for every candidate.

The reduction in high-motion-tail MAE was also distributed across the full range of time remaining before the target-station peak (Supplementary Fig. S8b). Across the six non-overlapping lead-time bins from 0–1 s to at least 20 s, relative PGA tail-MAE reductions ranged from {pga_min:.1f}% to {pga_max:.1f}%, whereas PGV reductions ranged from {pgv_min:.1f}% to {pgv_max:.1f}%. {timing_sentence} Even in the $\\geq20$-s subset, the paired changes were {float(pga_long['delta_caurc_minus_base']):+.3f} log10 units for PGA (95% confidence interval, {float(pga_long['delta_ci_lower']):+.3f} to {float(pga_long['delta_ci_upper']):+.3f}) and {float(pgv_long['delta_caurc_minus_base']):+.3f} for PGV ({float(pgv_long['delta_ci_lower']):+.3f} to {float(pgv_long['delta_ci_upper']):+.3f}). Thus, the aggregate improvement was not driven solely by targets whose remaining peaks occurred immediately after the causal snapshot.

Robustness to the station-matching definition was assessed using 10-, 20- and 30-km nearest-input-distance calipers while enforcing exact target P-wave-state matching and excluding all outcome variables from pair construction. The three analyses retained {pair_counts.get(10.0, 0):,}, {pair_counts.get(20.0, 0):,} and {pair_counts.get(30.0, 0):,} matched target pairs, respectively, while preserving all {int(balance['matched_events'].max())} test earthquakes (Supplementary Fig. S8c). {caliper_sentence} {bootstrap_sentence} (Supplementary Fig. S8d and Supplementary Table 8).

Together, these analyses show that the observed tail-MAE reduction is not confined to one feasible gate setting or one warning-lead stratum. They do not, however, establish invariance to every modelling decision. Observation-budget, tail-definition and independent-training-seed experiments are reported separately only after their corresponding models have been trained and locked; the present sensitivity analysis does not substitute for those experiments.
"""
    out_path.write_text(text, encoding="utf-8")


def write_required_experiments(out_path: Path) -> None:
    text = """REMAINING ROBUSTNESS EXPERIMENTS REQUIRED BEFORE A STRONG NATURE COMMUNICATIONS CLAIM

1. Observation budget (requires separate leakage-safe training for every setting)
   Recommended scenarios already supported by the manifest builder:
     T0=3 s, K=3
     T0=5 s, K=5  [primary]
     T0=10 s, K=5
     T0=10 s, K=10
   Do not evaluate the T0=5/K=5 checkpoint directly on a different feature horizon and call it
   robustness. Retrain and validation-lock the Base and CA-URC head within every scenario.

2. Tail definition
   Repeat the full train-only threshold construction and validation-only selection for Q85, Q90
   and Q95. Re-labelling the locked test set without retraining the risk head is not equivalent.

3. Severe-underprediction label
   Repeat the risk-head training for residual thresholds -0.3, -0.5 and -0.7 log10 units.
   Keep the primary endpoint (-0.5) unchanged and treat the others as sensitivity analyses.

4. Independent training seeds
   Prefer at least five independent seeds for both the Cross-Attention Base and the CA-URC head.
   Report seed-wise overall MAE, tail MAE, U0.5, selected epoch and selected gamma. The 20 target
   resampling repeats are not substitutes for independent model-training seeds.

5. Optional grouping sensitivity
   Rebuild sequence groups using nearby time/distance thresholds around the primary 30-day/30-km
   rule and repeat the grouped evaluation. This tests dependence on the leakage-control definition.

Until these runs exist, do not write that the method is robust to observation budget, tail quantile,
underprediction threshold or random initialization.
"""
    out_path.write_text(text, encoding="utf-8")


def table_to_latex(frame: pd.DataFrame, path: Path) -> None:
    path.write_text(frame.to_latex(index=False, escape=False, float_format=lambda x: f"{x:.4f}"), encoding="utf-8")


def write_outputs(
    gamma_scan: pd.DataFrame,
    selected: pd.Series,
    gamma_summary: pd.DataFrame,
    lead: pd.DataFrame,
    balance: pd.DataFrame,
    caliper: pd.DataFrame,
    bootstrap: pd.DataFrame,
    out_dir: Path,
) -> None:
    selection_table = gamma_summary.copy()
    selection_table["selected_gamma"] = np.isclose(selection_table["gamma"], float(selected["gamma"]))
    selection_table["selected_epoch"] = np.where(selection_table["selected_gamma"], int(selected["epoch"]), np.nan)
    selection_table.to_csv(out_dir / "TableS8_validation_selection.csv", index=False)
    table_to_latex(selection_table, out_dir / "TableS8_validation_selection.tex")

    lead_out = lead[
        [
            "quantity",
            "lead_bin",
            "cross_attention_value",
            "ca_urc_value",
            "delta_caurc_minus_base",
            "delta_ci_lower",
            "delta_ci_upper",
            "reduction_percent",
            "reduction_ci_lower",
            "reduction_ci_upper",
            "n_events",
        ]
    ].copy()
    lead_out.to_csv(out_dir / "TableS8_lead_time_sensitivity.csv", index=False)
    table_to_latex(lead_out, out_dir / "TableS8_lead_time_sensitivity.tex")

    caliper_out = caliper[
        [
            "caliper_km",
            "quantity",
            "n_events",
            "point_delta",
            "ci_lower",
            "ci_upper",
            "improvement",
            "matched_pairs",
            "matched_events",
            "median_abs_distance_difference_km",
        ]
    ].copy()
    caliper_out.to_csv(out_dir / "TableS8_station_caliper_sensitivity.csv", index=False)
    table_to_latex(caliper_out, out_dir / "TableS8_station_caliper_sensitivity.tex")

    bootstrap_out = bootstrap[
        [
            "quantity",
            "bootstrap_mode",
            "point_delta_candidate_minus_reference",
            "ci_lower",
            "ci_upper",
        ]
    ].copy()
    bootstrap_out.to_csv(out_dir / "TableS8_bootstrap_scheme_sensitivity.csv", index=False)
    table_to_latex(bootstrap_out, out_dir / "TableS8_bootstrap_scheme_sensitivity.tex")


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--gamma-scan",
        default=(
            "runs/cadrg_gate_ablation_A3_A5/A4_under_only/"
            "epoch_gamma_validation_scan.csv"
        ),
    )
    parser.add_argument(
        "--lead-bin-table",
        default="figures/nc_section_2_5/TableS5_metrics_by_peak_lead.csv",
    )
    parser.add_argument(
        "--matching-balance",
        default=(
            "runs/caurc_station_ood_matched_geometry/"
            "matching_balance_summary.csv"
        ),
    )
    parser.add_argument(
        "--matching-bootstrap",
        default=(
            "runs/caurc_station_ood_matched_geometry/"
            "matched_geometry_event_bootstrap.csv"
        ),
    )
    parser.add_argument(
        "--sequence-bootstrap",
        default=(
            "runs/caurc_sequence_aware_bootstrap/"
            "all_sequence_aware_bootstrap_summary.csv"
        ),
    )
    parser.add_argument("--out-dir", default="figures/nc_section_2_8")
    parser.add_argument("--dpi", type=int, default=600)
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--seed", type=int, default=20260713)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.demo:
        gamma_raw, lead_raw, balance_raw, station_boot_raw, bootstrap_raw = demo_inputs(args.seed)
        demo_dir = out_dir / "_demo_inputs"
        demo_dir.mkdir(parents=True, exist_ok=True)
        gamma_path = demo_dir / "gamma_scan.csv"
        lead_path = demo_dir / "lead_bins.csv"
        balance_path = demo_dir / "matching_balance.csv"
        station_boot_path = demo_dir / "matching_bootstrap.csv"
        bootstrap_path = demo_dir / "sequence_bootstrap.csv"
        gamma_raw.to_csv(gamma_path, index=False)
        lead_raw.to_csv(lead_path, index=False)
        balance_raw.to_csv(balance_path, index=False)
        station_boot_raw.to_csv(station_boot_path, index=False)
        bootstrap_raw.to_csv(bootstrap_path, index=False)
    else:
        gamma_path = Path(args.gamma_scan)
        lead_path = Path(args.lead_bin_table)
        balance_path = Path(args.matching_balance)
        station_boot_path = Path(args.matching_bootstrap)
        bootstrap_path = Path(args.sequence_bootstrap)
        for path in [gamma_path, lead_path, balance_path, station_boot_path, bootstrap_path]:
            if not path.exists():
                raise FileNotFoundError(path)

    gamma_scan, selected, gamma_summary = prepare_gamma_scan(gamma_path)
    lead = prepare_lead_sensitivity(lead_path)
    balance, caliper = prepare_caliper_sensitivity(balance_path, station_boot_path)
    bootstrap = prepare_bootstrap_sensitivity(bootstrap_path)

    make_figure(
        gamma_scan=gamma_scan,
        selected=selected,
        lead=lead,
        balance=balance,
        caliper=caliper,
        bootstrap=bootstrap,
        out_dir=out_dir,
        dpi=args.dpi,
        demo=args.demo,
    )
    write_outputs(
        gamma_scan,
        selected,
        gamma_summary,
        lead,
        balance,
        caliper,
        bootstrap,
        out_dir,
    )
    write_caption(
        gamma_scan,
        selected,
        lead,
        balance,
        out_dir / "FigS8_caption.txt",
    )
    write_manuscript(
        gamma_scan,
        selected,
        lead,
        balance,
        caliper,
        bootstrap,
        out_dir / "Section2_8_manuscript_draft.txt",
    )
    write_required_experiments(out_dir / "remaining_required_experiments.txt")

    config = {
        "demo": bool(args.demo),
        "locked_model": {"variant": "A4_under_only", "epoch": 3, "gamma": 5.0},
        "inputs": {
            "gamma_scan": str(gamma_path.resolve()),
            "lead_bin_table": str(lead_path.resolve()),
            "matching_balance": str(balance_path.resolve()),
            "matching_bootstrap": str(station_boot_path.resolve()),
            "sequence_bootstrap": str(bootstrap_path.resolve()),
        },
        "output_directory": str(out_dir.resolve()),
        "model_training_performed": False,
        "model_selection_performed": False,
        "figure_is_for_manuscript": not bool(args.demo),
    }
    (out_dir / "run_configuration.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )

    print("=== CA-URC robustness and sensitivity figure ===")
    print(f"Demo mode                  : {args.demo}")
    print(f"Validation candidates      : {len(gamma_scan)}")
    print(f"Feasible candidates        : {int(gamma_scan['feasible'].sum())}")
    print(
        "Locked selection           : "
        f"epoch={int(selected['epoch'])}, gamma={float(selected['gamma']):g}"
    )
    print(f"Lead-bin rows              : {len(lead)}")
    print(f"Station-caliper rows       : {len(caliper)}")
    print(f"Bootstrap-scheme rows      : {len(bootstrap)}")
    print("Outputs:")
    for path in sorted(out_dir.iterdir()):
        if path.is_file():
            print(f"  {path.resolve()}")


if __name__ == "__main__":
    main()
